### PR TITLE
Change: Enable and fix audio for USA Battle Drone repairs

### PR DESCRIPTION
**Pull request by xezon**
This change enables and fixes audio for USA Battle Drone repairs.

The sound files already existed, but had some humming and quite "crispy" sparks. I reduced the humming and made the sparks less "crispy", so they do not jump as much into the ears. Thus they sound subtle in 3d world.

https://user-images.githubusercontent.com/4720891/198886343-1d8d3a52-3493-4942-820a-b63943fe9c8c.mp4

https://user-images.githubusercontent.com/4720891/198886354-791f6877-456e-4d72-8292-da2a6ad13b1f.mp4

### CODE REVIEW

**Comment by MTKing4** [comment]
What is the sound limit on this?

**Comment by xezon** [comment]
4

**Comment by xezon** [comment]
Works.

shot_20221030_163458_2

**Comment by MTKing4** [comment]
felt a bit too much, maybe reducing it to 3 or 2 could be better

**Comment by xezon** [comment]
Ok. Reduced limit from 4 to 3.

**Comment by xezon** [comment]
The wav files contained meta data. Removed, saved 10 KB.

**Comment by xezon** [comment]
Looks okay.

**Pull request merged**
