### PR TITLE
Test Branch Helix AI / Helix Gatling Changes

### PR DESCRIPTION
**Pull request by commy2**

### CODE REVIEW

**Comment by MTKing4** [comment]
https://user-images.githubusercontent.com/83613147/137638065-ebd7497f-e03b-41e1-8e07-dc92c7d9ae78.mp4

https://user-images.githubusercontent.com/83613147/137638079-3cc92d25-3344-4a8d-a948-f39551605991.mp4


https://user-images.githubusercontent.com/83613147/137638100-5e28755e-d998-4a9f-9616-f70f753b10b5.mp4

https://user-images.githubusercontent.com/83613147/137638113-53f5e109-d546-494f-b660-d68ff7fcf1af.mp4



https://user-images.githubusercontent.com/83613147/137638122-e34978f5-f86b-4537-ad61-0fbb0afe8d2f.mp4

https://user-images.githubusercontent.com/83613147/137638145-e42b76d0-16e7-40bd-aaec-639879f92f84.mp4


https://user-images.githubusercontent.com/83613147/137638153-e013be72-bfbf-43bd-ba6d-84b20e3fe5dd.mp4


https://user-images.githubusercontent.com/83613147/137638158-29853843-0c8b-4444-9a1b-9cb6196db08b.mp4



https://user-images.githubusercontent.com/83613147/137638169-9d4b4455-a4b7-4119-ac4d-835f9d8eb221.mp4


https://user-images.githubusercontent.com/83613147/137638181-ac47cdfe-a7ce-4600-8dd8-b1d0b31adbe4.mp4

https://user-images.githubusercontent.com/83613147/137638198-6423857b-473f-472f-916f-cd78e903156d.mp4


https://user-images.githubusercontent.com/83613147/137638208-10c47fe3-f84f-44ef-a421-e92dfb279cee.mp4


https://user-images.githubusercontent.com/83613147/137638222-102b6da9-5751-4b7f-8b57-5fff6b53f0fd.mp4


https://user-images.githubusercontent.com/83613147/137638231-20d60080-f2e7-4d06-8568-1b58ac9e159f.mp4


https://user-images.githubusercontent.com/83613147/137638244-0aedfa51-4d10-4ad5-b374-41138ea0ce9d.mp4



https://user-images.githubusercontent.com/83613147/137638262-fb9860b1-92b3-485b-81d5-39d89f44d66b.mp4


https://user-images.githubusercontent.com/83613147/137638272-f667c76b-4f3d-4aca-8e0e-f89cbb0897c9.mp4


https://user-images.githubusercontent.com/83613147/137638282-e3ca40bd-e947-45f6-a2dc-f0c2985d2579.mp4


https://user-images.githubusercontent.com/83613147/137638293-92f0a6eb-f30f-4f77-8cb6-66000960210f.mp4


https://user-images.githubusercontent.com/83613147/137638310-6c0569c6-df4d-40bd-976c-e8d84a02e1a0.mp4

https://user-images.githubusercontent.com/83613147/137638335-81690960-ae0d-4462-9329-a820b79e68af.mp4


https://user-images.githubusercontent.com/83613147/137638350-2d86187c-685a-47d9-a784-2739ba89a7f0.mp4


https://user-images.githubusercontent.com/83613147/137638369-5a863c2f-f92d-4ea0-83a3-0cbe7742e5c5.mp4


https://user-images.githubusercontent.com/83613147/137638385-5a3f0b54-0442-4cab-aa2c-d8a8411e4cba.mp4


https://user-images.githubusercontent.com/83613147/137638424-0f2a63a0-843e-4972-87ec-422866c4dbd5.mp4

**Comment by MTKing4** [comment]
replays of tests with their relevant test maps included in link below
[TestsReplays.zip](https://github.com/xezon/GeneralsGamePatch/files/7360538/TestsReplays.zip)

**Comment by ExiLe-ZH** [comment]
These airbattles look massively different from 1.04, normally the missiles don't have the range to hit escaping Lixes. So both players have to make tactical turns in order to kill the enemy Lixes. Here it is much more like click and chase.

**Comment by MTKing4** [comment]
> These airbattles look massively different from 1.04, normally the missiles don't have the range to hit escaping Lixes. So both players have to make tactical turns in order to kill the enemy Lixes. Here it is much more like click and chase.

You are correct, they are different, but this has been discussed before, when mini gunner helix range bug was discussed here #342 it was agreed by everyone that you should be able to target air units manually with inf lix, therefore this was made as the logical response for other Chinas.

So with minilix being able to target air units, you will have differences with air battles regardless of the gatlix change.

**Pull request closed without merging**
