### PR TITLE
Balance: Invert and Redistribute Quad Cannon Guns DPS

### PR DESCRIPTION
**Pull request by xezon**
Reference issue:
* #56

This change redistributes the Quad veterancy damage values so that VETERAN has the least bonus damage and HERO has the most. The sum of all bonus is identical to the sum of all original bonus. A Quad Cannon with veterancy and without scrap will now deal about the same damage as a China Gatling Tank with veterancy. Before it dealt around 33% damage more than its Gatling Tank counterpart. Quad Cannon will unleash full potential with scrap upgrades only, where it will deal up to around 33% more damage than Gatling Tank.

## Original
before

## Patched
after

## Original
https://user-images.githubusercontent.com/4720891/182035421-266e6e12-fce2-44ca-a4f5-2abe67ba91e7.mp4

## Patched
https://user-images.githubusercontent.com/4720891/182035426-c30d780b-54f5-4b0e-86d9-7c86c4916b3b.mp4

### CODE REVIEW

**Comment by xezon** [comment]
I attached comparison video for this one. Please check.

**Comment by xezon** [comment]
I fixed the logic issue in the DPS calculator, and recalculated the correct modifiers for the intended target values. New comparison videos have been added to first post. The old stats images remain correct.

**Comment by ExiLe-ZH** [comment]
New damage model looks very promising, I would love to see a direct test of Quads vs Gats.

I'm hoping 1 Scrap makes performance exactly similar to Gatling Tanks and 2 Scraps a tiny bit better.

**Comment by xezon** [comment]
I tested Unscrapped Quad vs Gatt. Here are relevant results. Table shows winner with rough percentage of health left, judged by health bar.

## Original Unscrapped Quad vs Gatt, No Pre Spin

|  VS       | Vet0 Quad | Vet1 Quad | Vet2 Quad | Vet3 Quad |
|-----------|-----------|-----------|-----------|-----------|
| Vet0 Gatt | Gatt 20%  |           |           |           |
| Vet1 Gatt |           | Quad 30%  |           |           |
| Vet2 Gatt |           | Quat 15%  |           |           |
| Vet3 Gatt |           | Gatt 2%   | Quad 5%   |           |

## Original Unscrapped Quad vs Gatt, WITH PRE SPIN

|  VS       | Vet0 Quad | Vet1 Quad | Vet2 Quad | Vet3 Quad |
|-----------|-----------|-----------|-----------|-----------|
| Vet0 Gatt | Gatt 30%  |           |           |           |
| Vet1 Gatt |           | Quad 20%  |           |           |
| Vet2 Gatt |           | Quad 5%   | Quad 20%  |           |
| Vet3 Gatt |           | Gatt 5%   | Quad 2%   |           |

## Patched Unscrapped Quad vs Gatt, No Pre Spin

|  VS       | Vet0 Quad | Vet1 Quad | Vet2 Quad | Vet3 Quad |
|-----------|-----------|-----------|-----------|-----------|
| Vet0 Gatt | Gatt 20%  |           |           |           |
| Vet1 Gatt |           | Quad 5%   |           |           |
| Vet2 Gatt |           | Gatt 5%   | Quad 5%   |           |
| Vet3 Gatt |           |           | Gatt 15%  | Quad 1%   |

## Patched Unscrapped Quad vs Gatt, WITH PRE SPIN

|  VS       | Vet0 Quad | Vet1 Quad | Vet2 Quad | Vet3 Quad |
|-----------|-----------|-----------|-----------|-----------|
| Vet0 Gatt | Gatt 30%  |           |           |           |
| Vet1 Gatt |           | Gatt 2%   |           |           |
| Vet2 Gatt |           |           | Gatt 1%   |           |
| Vet3 Gatt |           |           |           | Gatt 1%   |


# Conclusion

China Gattling has better fighting chance with this change, but Quad still wins in direct 1v1 on same veteran level if the Gattling is not spun up, albeit just barely surviving. If Gattling is spun up, it will just barely win and survive with the health bar pretty much empty. Quad would require real nerf for Gattling to be more comfortable. Or the Gattling a buff. Either in weapon or armor.

**Comment by xezon** [comment]
Jundiyy:
> It seems reasonable, especially since vet 0 has been kept the same, which I think is very important. Since most of the units will be vet 0. Changes seem good but perhaps they have been tweaked a bit too much?

**Pull request closed without merging**
