### PR TITLE
Fix: Improve English sound quality by removing hum, noise, hiss and crackling

### LINKED ISSUE #1058: Some audio lines have humming recorded into them
Some audio lines have humming recorded into them.

Example: Data\Audio\Sounds\English\vtromoe.wav

Perhaps cleanup those sounds that are most affected by this.

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Fixes #1058

This change fixes humming, noises, hissing and crackling for all Unit and EVA sounds. It uses 72 MB uncompressed and 58 MB 7-zip compressed. Due the large size requirement it is therefore unfit for Patch Core and will be optional content only.

The sounds are bundled into the following archives:
* OptionalAudioArabic
* OptionalAudioBrazilian
* OptionalAudioChinese
* OptionalAudioEnglish
* OptionalAudioFrench (uses just a few of the sounds)
* OptionalAudioItalian
* OptionalAudioKorean
* OptionalAudioPolish
* OptionalAudioSpanish

# Affected units

## USA

* Ranger
* Laser Ranger
* Missile Defender
* Pathfinder
* Burton
* Dozer
* Humvee
* Ambulance
* Crusader
* Microwave
* Combat Chinook
* Comanche
* Raptor
* Stealth Fighter
* Aurora
* Spectre Gunship

## China

* Red Guard
* Minigunner
* China Lotus
* Hacker
* Dozer
* ECM
* Troop Crawler
* Listening Outpost
* Inferno Cannon
* Nuke Cannon
* Overlord
* Helix

## GLA

* Worker
* GLA Rebel
* GLA Tunnel Defender
* Hijacker
* Jarmen
* Saboteur
* Terror
* Car Bomb
* Cycle
* Toxin Tractor
* Technical
* Quad
* Scorpion
* Radar Van
* Rocket Buggy
* Bomb Truck
* SCUD
* Marauder
* POW

### CODE REVIEW

**Comment by commy2** [comment]
I do not think this is necessary and fear for hidden regressions when mass replacing asset files. I would rather the game sounds the same as it does now than apply any unknown tweaks. 

This also inflates the patch size.

**Comment by xezon** [comment]
If there are issues with it, please show them.

As for size, this is optional content, thus no concern for Patch Core size.

**Comment by commy2** [comment]
> this is optional content

Excellent news! I too would put this into a category like Control Bar HD / Pro. If it is optional, preferably opt-in, then I have nothing agains this being part of the project.

**Comment by xezon** [comment]
The opening post does say "OptionalAudioEnglish" and the change also shows that it is bundled into optional packs. I will reword opening post so it becomes more obvious. As said in Discord: There is no way any optional fixes and improvements are getting blocked by purist opinion. As for Control Bar Pro Addon, that is complete redesign of Control Bar and thus cannot and should not be part of this project. As for these sounds, they are a direct improvement of original content and thus perfectly fit in here. Due the large bandwidth requirements it is evident that it should not be part of the core files.

**Comment by xezon** [comment]
I made another pass on all sounds. All wav files (uncompressed) have been re-exported without meta data, saving 3.8 MB in total.

All sounds have been reviewed and more clicks have been removed. Some sounds also had a bit of noise or hum left over.

Additionally a few vehicle effects were fixed, most notable clicks in Helix Ambient Loops and Dragon Tank Attack, Decay. These clicks are caused if the start or end of a loop are not at 0 dB.

From my side this task is now complete.

**Comment by xezon** [comment]
I did another review pass on all fixed sounds and fixed a few more things on around 60 of them. Next step for this is to split audio into smaller commit chunks to have a bit of an overview what was touched from commit.

**Comment by xezon** [comment]
Last days I did a couple more review passes over the already touched wav files and fixed clicks, fadein, fadeout and other issues in 166 audio files.

I also put the wav files in new subfolders, accompanied the files with a note about what was changed and splitted the commits into smaller chunks.

I think this really looks (sounds) good now.

**Comment by xezon** [comment]
121 EVA sounds were remade with 44100 hz sampling.

**Pull request merged**
