### PR TITLE
Change: Tweak USA Drone shroud ranges

### LINKED ISSUE #983: USA Scout and Hellfire drone have astonishing Cloud Clearing Range, Battle Drone does not
USA Scout and Hellfire drone have astonishing Cloud Clearing Range, Battle Drone does not.

| Object                           | Shroud Clearing Range | Area       |
|----------------------------------|-----------------------|-----------:|
| Original USA Sentry Drone        | 350                   | 384845     |
| Original USA Scout Drone         | 500 (+75+10 wander)   | min 785398 |
| Original USA Battle Drone        | 150 (+75+10 wander)   | 70685      |
| Original USA Hellfire Drone      | 500 (+75+10 wander)   | min 785398 |
| Original USA Humvee              | 320                   | 321699     |
| Original USA Missile Defender    | 400                   | 502654     |
| Original China Outpost           | 500                   | 785398     |
| Original China Lotus             | 400                   | 502654     |

### PR DESCRIPTION
**Pull request by xezon**
* old PR #990
* Fixes #983

This change increases ShroudClearingRange of USA Battle Drone from 150 to 300 and decreases it of USA Hellfire Drone from 500 to 400.

| Object                           | Attack Range | Shroud Clearing Range | Area   | Adv. over Battle | Adv. over Hellfire |
|----------------------------------|--------------|-----------------------|--------|------------------|--------------------|
| Original USA Battle Drone        |              | 150 (+75+10 wander)   | 70685  |                  |                    |
| Original USA Hellfire Drone      | 150          | 500 (+75+10 wander)   | 785398 | +1011%           |                    |
| Original USA Scout Drone         | 110          | 500 (+75+10 wander)   | 785398 | +1011%           | +0%                |
| Patched USA Battle Drone (this)  |              | 300 (+75+10 wander)   | 282743 |                  |                    |
| Patched USA Hellfire Drone (this)| 150          | 400 (+75+10 wander)   | 502654 | +77%             |                    |
| Patched USA Scout Drone (this)   | 110          | 500 (+75+10 wander)   | 785398 | +177%            | +56%               |

## Other objects for reference

| Object                           | Shroud Clearing Range | Area       |
|----------------------------------|-----------------------|-----------:|
| Original USA Sentry Drone        | 350                   | 384845     |
| Original USA Humvee              | 320                   | 321699     |
| Original USA Missile Defender    | 400                   | 502654     |
| Original China Outpost           | 500                   | 785398     |
| Original China Lotus             | 400                   | 502654     |

# Rationale

The original Hellfire drone has a massive sight of 500 matching the Scout Drone. It costs 5 times as much as the Scout Drone, but it also has a good weapon and much more armor. The original Battle drone has a useless sight of just 150. Since most USA Tanks have a sight of 300, the Battle drone sight adds nothing in practice.

With the readjusted shroud ranges the Scout drone retains its pristine range of 500. The Hellfire shroud range is reduced a little bit, but can still see much more than all USA vehicles by a large margin. The range was not reduced further because it is the most expensive drone and it is a much less consequential change to tweak the range just as much as this change does. Meanwhile the Battle Drone now sees as far as most USA Tanks, and since it sways around its host vehicle, it will increase the shroud range just a bit while it sways. For most practical purposes, the Battle drone will not provide a tangible gain in shroud range. However, since the Hellfire Drone has a decreased shroud range, it is just fair to give the Battle Drone a larger shroud range to compensate. The Tomahawk + Battle Drone will benefit from this, because Tomahawk has a shroud range of just 200.

The new ranges offer a more logical distribution of shroud clearing ranges and make the Scout Drone more unique with its very large shroud range. Since the Scout Drone just costs 100, it is always easily accessible and a USA player can afford one to benefit of its perks.

| Object                           | Perks                                      |
|----------------------------------|--------------------------------------------|
| Patched USA Battle Drone (this)  | Machine Gun, Good Armor, Repair ability    |
| Patched USA Hellfire Drone (this)| Best Weapon, Best Armor, Good Shroud Range |
| Patched USA Scout Drone (this)   | Stealth Detection, Best Shroud Range       |

# Media

## Original Battle Drone

original_battle

## Original Hellfire Drone

original_hellfire

## original Scout Drone

original_scout

## Patched Battle Drone

patched_battle

## Patched Hellfire Drone

patched_hellfire

### CODE REVIEW

**Comment by xezon** [comment]
Reduce Hellfire Range of 400 further but give Sentry Drone more shroud range.

**Comment by Jundiyy** [comment]
👍

**Comment by xezon** [comment]
Is this change good to go?

**Comment by xezon** [comment]
Shroud ranges look reasonable.

**Pull request merged**
