### PR TITLE
Alpha aurora portrait art

### PR DESCRIPTION
**Pull request by MTKing4**
added alpha aurora portrait art with 2 variations

+ with USA Default teamcolor Blue
+ with Neutral Civilian Color Gray

### CODE REVIEW

**Comment by xezon** [comment]
There is a "ControlBarPro" in the path name.

**Comment by xezon** [comment]
Instead of closing and reopening a Pull Request, you can just append to a Pull Request by pushing new changes to it.

**Comment by MTKing4** [comment]
ok didn't know that. the reason this happened is because i had a typo in the branch name and when i renamed it git just closed and deleted the old branch name automatically so i had to remake the pr, second closed pr I guess is the pr with that git made for me when i changed the name? didn't notice that until now

anyway is this good for now?

**Comment by xezon** [comment]
Just remove the "Pro" in the "ControlBar" folder name.

**Comment by MTKing4** [comment]
done

**Comment by xezon** [comment]
Stubbjax already made a better version of this, so I think we can close this one, yes?

**Comment by MTKing4** [comment]
Yes, closed

**Pull request closed without merging**
