### PR TITLE
Change: Add new sound for Demo Trap select

### PR DESCRIPTION
**Pull request by xezon**
This change adds better fitting sound for Demo Trap select.

## Original

Plays generator sound on Demo Trap select.

https://user-images.githubusercontent.com/4720891/188462853-54203e09-b436-440e-a640-c3cd9d98baa5.mp4

## Patched Core Sound

Plays machinery on Demo Trap select.

https://user-images.githubusercontent.com/4720891/188566739-e5b3d67e-1eb3-4e52-8544-366db6459ef6.mp4

## ~~Patched Optional Sound~~

~~Plays beeps and machinery on Demo Trap select.~~

https://user-images.githubusercontent.com/4720891/188566756-a73ac5f3-e3f8-4089-9c15-01cff1fe891f.mp4

### CODE REVIEW

**Comment by commy2** [comment]
Hmm, while the original sound is strange, this new one sounds very similar to a demo trap about to blow up. This will require getting used to and may be confusing.

**Comment by xezon** [comment]
It should sound different, because the pitch of the beeps is different and it has longer gaps between the beeps.

**Comment by ExiLe-ZH** [comment]
Good improvement, original sounds out of place.

**Comment by xezon** [comment]
The beeping sound is now optional content. I added another sound into core files without the beeping.

**Comment by MTKing4** [comment]
I like it, commy has a point though, no preference for me either way.

**Comment by xezon** [comment]
I am removing the Controversial label because the sound without the beeping is now a clean substitute for the original generator sound which should come without annoyance.

**Comment by MTKing4** [comment]
A demonstration of the new edited sound?

**Comment by xezon** [comment]
New videos added.

**Comment by xezon** [comment]
Any further opinions on this? From my side is is ok, although I am not sure how the beeping select will experience in actual match. Would have to be tested, but can be changed again if deemed annoying.

**Comment by xezon** [comment]
I removed the optional sound with beeping for now. This way this change is less likely to cause upset.

**Pull request merged**
