### PR TITLE
Fix: Delete Immortal Aurora Wrecks Circling In Air

### PR DESCRIPTION
**Pull request by commy2**
Please ignore the Nuke and the Migs. I needed a savegame where this reliably happens after load for debugging.

https://user-images.githubusercontent.com/6576312/187041891-093f65c0-268b-4088-9852-e5059d531728.mp4

They still bug out and circle, but the spectactle will be cleaned up after 10 seconds maximum. This is the best I can do with INI scripting.

### CODE REVIEW

**Comment by xezon** [comment]
"Ahhhhhhh ahhhhhhhhh ahhhhhhhhhhh" they scream. I think this tweak is still better than infinite circling ones. Is there a reason you chose 10 seconds specifically?

**Comment by commy2** [comment]
Just a conservative number to not prematurely delete actually falling wrecks.

Most ground units seem to have values around 2 seconds for the wreck to disappear.

It could possibly be shortened. It doesn't look like a non stuck Aurora will fall for near 10 seconds.

Although this bug is rare. And this is a hack. It will always look dumb. Idk.

**Comment by xezon** [comment]
Just judging by the video, it took around 6 seconds between death and sunken in terrain for the wreck to be gone. 10 is conservative indeed. Probably is fine as is.

**Review by xezon — APPROVED** [review]

**Comment by commy2** [comment]
Objects with the same setup:

```ini
AmericaJetRaptor
AirF_AmericaJetRaptor (King Raptor)
Lazr_AmericaJetRaptor
SupW_AmericaJetRaptor
Boss_JetRaptor (King Raptor)
AmericaJetAircraftCarrierRaptor (USA02 campaign)

AmericaJetStealthFighter
AirF_AmericaJetStealthFighter
Lazr_AmericaJetStealthFighter
SupW_AmericaJetStealthFighter

AmericaVehicleChinook
AirF_AmericaVehicleChinook (Combat Chinook)
Lazr_AmericaVehicleChinook
SupW_AmericaVehicleChinook
AFG_AmericaVehicleChinook

AmericaVehicleComanche
AirF_AmericaVehicleComanche
Lazr_AmericaVehicleComanche
SupW_AmericaVehicleComanche

AmericaJetA10Thunderbolt
AirF_AmericaJetA10Thunderbolt (unused)
Lazr_AmericaJetA10Thunderbolt (unused)
SupW_AmericaJetA10Thunderbolt (unused)

AmericaJetSpectreGunship
AirF_AmericaJetSpectreGunship1
AirF_AmericaJetSpectreGunship2
AirF_AmericaJetSpectreGunship3
Lazr_AmericaJetSpectreGunship (unused)
SupW_AmericaJetSpectreGunship (unused)
Boss_JetSpectreGunship (unused)

ChinaJetMIG
Infa_ChinaJetMIG
Tank_ChinaJetMIG
Nuke_ChinaJetMIG
Boss_JetMIG

ChinaVehicleHelix
Infa_ChinaVehicleHelix
Tank_ChinaVehicleHelix
Nuke_ChinaVehicleHelix
Boss_VehicleHelix
```

**Pull request closed without merging**
