### PR TITLE
Fix: Added missing shadow to the fat guy with the tank top.

### PR DESCRIPTION
**Pull request by Stubbjax**
Before:

image

After:

image

### CODE REVIEW

**Review by xezon — APPROVED** [review]
Very generous shadow size for his belly size.

**Comment by Stubbjax** [comment]
> Very generous shadow size for his belly size.

We could make it slightly larger than the others?😄

**Comment by xezon** [comment]
You can try :)

**Comment by Stubbjax** [comment]
> You can try :)

14 → 16

image

**Comment by commy2** [comment]
Fatso is sus

**Comment by commy2** [comment]
Is this a 1.04 thing to or did I break it? If 1.04, put in eventual changelog, otherwise, don't.

**Comment by Stubbjax** [comment]
> Is this a 1.04 thing to or did I break it? If 1.04, put in eventual changelog, otherwise, don't.

Ah yeah, the shadow does display in 1.04. I'll correct that.

**Comment by ExiLe-ZH** [comment]
> Very generous shadow size for his belly size.

Correct shadow size would kill the performance.

And make any map a night map.

Bug is deliberate most likely.

**Comment by commy2** [comment]
Caused by https://github.com/TheSuperHackers/GeneralsGamePatch/pull/906.

**Comment by commy2** [comment]
"Increased Shadow Size Of Obese Angry Mob Member" should totally appear in the eventual changelog.

**Review by xezon — APPROVED** [review]

**Review by commy2 — APPROVED** [review]

**Pull request merged**
