### PR TITLE
Fix GLA Terrorist passenger crash

### PR DESCRIPTION
**Pull request by alanblack166**
Terrorists crashed the game in two scenarios. This commit fixes the crash in both instances.

### CODE REVIEW

**Comment by commy2** [comment]
This is WIP.

**Comment by xezon** [comment]
What is missing?

**Comment by alanblack166** [comment]
Need to finish the other generals.

**Comment by commy2** [comment]
Also currently the added deaths are handled by two SlowDeath modules. See ModuleTag_Death01. This will make the game chose one at random.

**Comment by xezon** [comment]
Crash is still reproducible.

**Comment by xezon** [comment]
Potentially obsolete by change
* #699

However, does this change still have use? Test if suicide in this branch behaves any better.

**Comment by commy2** [comment]
If the bug is fixed, this PR is superseded.

**Comment by xezon** [comment]
I tested.

I am unable to observe any difference in damage output of Original vs Hanfield change. Both Terror in Technical and Battle Bus incur big damage on blow up. Behaviour on China mines also looks identical. The only difference I can observe are the visuals during blow up, where in this change the terrorists and their particles are visible during the death of the vehicle, which looks visually much more impressive. If we care for this visual, then this change seems cool.

## Original Bang bus blow up

shot_20220720_162908_1

## Original Bang bus aftermath

shot_20220720_162909_2

## New Bang bus blow up

shot_20220720_162742_1

## New Bang bus aftermath

shot_20220720_162744_2

**Comment by xezon** [comment]
I will wrap up this change some time soon. Change is nice.

**Comment by xezon** [comment]
I now tweaked the change as much as I can and tested Terrorist killing, crushing and driving over mines. All looked good. Crushing Terrorist in Vehicle will just kill it without them exploding in both Original and Patch. Sometimes the Terrorist just evacuate and survive when driving over mines, but that also happens in both Original and Patch. I did not apply the changes to non Skirmish Factions, because with GC_Chem the setup would be a nightmare.

**Comment by commy2** [comment]
So what exactly changed here? From my understanding, the CTD was already fixed by removing the bugged suicide weapon from the Tox Terrorist.

**Comment by xezon** [comment]
The only thing I see changed here is what you can see in the images above. The terrorists and their effects are visible when their host vehicle dies. Other than that it appears to behaves the same.

**Comment by commy2** [comment]
I see. So this is an entirely visual change. Pull request title should reflect that.

**Comment by xezon** [comment]
Done.

**Comment by commy2** [comment]
DestroyRidersWhoAreNotFreeToExit  is added to vGLA Bus, but not the others.

**Comment by alanblack166** [comment]
Maybe because the commit is not final?

**Comment by xezon** [comment]
> DestroyRidersWhoAreNotFreeToExit is added to vGLA Bus, but not the others.

Oh right, I forgot. Will add them :)

**Comment by xezon** [comment]
After a bit more conversation on Discord about it, we figured proper fix for the original crash issue. This fix now no longer crashes the game with GLA Terrorists in specific scenarios.

**Comment by xezon** [comment]
I had to revert the changes to GC_Chem because the crashed the game on load.

**Comment by xezon** [comment]
Maybe close. Not sure.

**Pull request closed without merging**
