### PR TITLE
Null clip sizes of all stream weapons

### PR DESCRIPTION
**Pull request by xezon**
This change nulls the clip sizes of all stream weapons. Some stream weapons already have this setup. Game play wise this makes no difference.

### CODE REVIEW

**Comment by xezon** [comment]
This change requires no further documentation.

**Comment by commy2** [comment]
As far as I can tell, this changes how Ambo Detox ability works, as the button fires 1 full clip.

**Comment by xezon** [comment]
I expect that it fired until the puddle is deleted. The clip reload was instant.

**Comment by commy2** [comment]
ClipReload is instant, but it fires 30 shots * DelayBetweenShots=40

**Comment by xezon** [comment]
Ok. It is not really clear to me if this could make a difference somehow. Perhaps there is a Script Action or an AI behavior which says "fire one clip of your weapon" and if we changed this perhaps behavior would change unexpectedly. Right now firing 1 clip would mean all (most) these stream weapons shoot for 2 seconds.

So we can close this.

**Pull request closed without merging**
