### PR TITLE
Match Gattling barrel spin animation speeds with fire rates

### PR DESCRIPTION
**Pull request by xezon**
This change matches all Gattling barrel spin animation speeds with their respective fire rates.

This change has multiple commits and should be Merged with Rebase.

The new animation speeds were determined by observing the individual fire rates, barrel spins frame by frame and adjusting the animation speeds accordingly. Surely there is some math to it, but I did not check it.

### CODE REVIEW

**Review by commy2 — APPROVED** [review]
lgtm
Only worry is, that making effects slower for Gatling tank means, it won't match when vetted.

**Comment by xezon** [comment]
Hmm good point. I did not test that. Perhaps for Gattling Tank we would need to set speed to somewhere between firing rate of Vet 0 and Vet 3. Does Overlord/Helix Gattling Cannon change on Veterancy?

**Comment by commy2** [comment]
> Does Overlord/Helix Gattling Cannon change on Veterancy?

I don't think so. No red tracers at least.

**Comment by xezon** [comment]
I tested Gattling Tank CONTINUOUS_FIRE_FAST on Vet 1 with RATE_OF_FIRE 120% and Vet 3 with RATE_OF_FIRE 160%, and the muzzle flashes have exact same interval as with Vet 0 with RATE_OF_FIRE 100%. So the barrel spin remains a match. I think there is nothing more to do here.

**Pull request merged**
