### PR TITLE
Fix: China Nuke Cannon animation jumps while it creeps forward after firing

### LINKED ISSUE #1651: China Nuke Cannon turret jumps animation when targeting
China Nuke Cannon turret jumps animation when targeting.

Tested with Nuke Cannon from Regular China and Nuke General.

https://user-images.githubusercontent.com/4720891/217897904-03ce7725-9078-411b-9987-b7574bddcb00.mp4

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1651

This change fixes China Nuke Cannon animation jump while vehicle creeps forward after firing.

https://user-images.githubusercontent.com/4720891/218319935-7506c461-6ad3-40b8-8535-562e1d449e33.mp4

### CODE REVIEW

**Comment by commy2** [comment]
Does it work with Neutron Shells?

**Comment by xezon** [comment]
Yes.

**Comment by MTKing4** [comment]
Is it a confirmed fix with no side effects? If so it should be merged

Also maybe some details on how it got fixed would be nice

**Comment by xezon** [comment]
You can clone the branch and check in game to see if it works properly. You can see how it was fixed in the Files changed diff.

**Comment by xezon** [comment]
Works.

**Comment by Stubbjax** [comment]
So all this does is make the bug look a bit nicer?

**Comment by xezon** [comment]
Yes. As for fixing the creeping, I do not know yet how to solve it. Possibly code bug.

**Pull request merged**
