### PR TITLE
Fix: excleanupstream texture

### PR DESCRIPTION
**Pull request by xezon**
This change fixes the excleanupstream texture color for the USA Ambulance cleanup stream. It now matches the particle colors better.

## Original

shot_20230624_171120_1

## Patched

shot_20230624_171255_1

### CODE REVIEW

**Comment by commy2** [comment]
Idk, I like the contast of the original more.

**Comment by MTKing4** [comment]
There's a merit to the original colors, it makes the stream distinct from its particles, right now they're just one entity

**Comment by xezon** [comment]
Perhaps there is another way to fix it, by shifting particle colors from cyan to purple.

**Comment by xezon** [comment]
Obsolete by #2041

**Comment by commy2** [comment]
This IS https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2038

**Pull request closed without merging**
