### PR TITLE
Fix: Set EXPLODED death type for weapon of USA Missile Defender

### PR DESCRIPTION
**Pull request by xezon**
This change sets the expected EXPLODED death type for the weapon of the USA Missile Defender. It is now consistent with weapons of Tank Hunter and RPG Trooper.

The major consequence is that the missiles will now explode the GLA Terrorists and therefore trigger their suicide weapon. It will also trigger the suicide weapon of the GLA Demo Bike before Demolitions Upgrade.

This is a fix but also nerf on USA.

## Original

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/9f71ba02-2f89-4265-a88b-e1a7358c885b

### CODE REVIEW

**Comment by xezon** [comment]
I do wonder, will this have any other gameplay consequences?

**Comment by penfriendz** [comment]
Looks good to me.

**Comment by MTKing4** [comment]
Seems Fair to me

**Comment by xezon** [comment]
The Demo Bikes are also affected - before Demo Upgrade.

Fixing this bug means that Demo General could spam Demo Bikes against USA before Demo Upgrade and see higher success rates.

The Humvee TOW missile and Hellfire Drone missile will also trigger the suicide weapons of Terrorists and Demo Bikes.

### Original

USA Missile Defender will **NOT** trigger suicide weapon of Demo Bike before Demo Upgrade.
USA Missile Defender will trigger suicide weapon of Demo Bike after Demo Upgrade.

China Tank Hunter will trigger suicide weapon of Demo Bike before Demo Upgrade.
China Tank Hunter will trigger suicide weapon of Demo Bike after Demo Upgrade.

GLA RPG Trooper will trigger suicide weapon of Demo Bike before Demo Upgrade.
GLA RPG Trooper will trigger suicide weapon of Demo Bike after Demo Upgrade.

### Patched

USA Missile Defender will trigger suicide weapon of Demo Bike before Demo Upgrade.
USA Missile Defender will trigger suicide weapon of Demo Bike after Demo Upgrade.

China Tank Hunter will trigger suicide weapon of Demo Bike before Demo Upgrade.
China Tank Hunter will trigger suicide weapon of Demo Bike after Demo Upgrade.

GLA RPG Trooper will trigger suicide weapon of Demo Bike before Demo Upgrade.
GLA RPG Trooper will trigger suicide weapon of Demo Bike after Demo Upgrade.

**Comment by penfriendz** [comment]
Seems like biggest difference will be humvees vs demo bikes pre upgrade.

But I'm totally fine with that from a balance perspective. Now it finally makes sense!

**Comment by ExiLe-ZH** [comment]
This depends on how good (pre-upgrade) dbs actually become vs vees.

**Comment by commy2** [comment]
It does not change dps. death type is not the same as damage type.

**Comment by penfriendz** [comment]
> This depends on how good (pre-upgrade) dbs actually become vs vees.

Not really. Humvees already kill dbs with ease. I never find upgraded dbs unfair vs USA and every time I lose a vee to them I only blame myself.
I feel sorry for China. I don't think I've ever seen their units move. At least humvees can.
There will be no difference to mid level players or above.

**Comment by ExiLe-ZH** [comment]
Don't disagree thats it's usually very avoidable to get hit in the game dynamic we currently have. That's the dynamic where USA already has multiple vees before the first bike is produced, also often supported with S&D.

With this change the dynamic changes, where the first bike is ready before the first vee. This might totally change the numbers game and this is where it might get hard, having to stop big blobs without S&D.

**Comment by xezon** [comment]
Yes. It will likely lead to scenarios where Demo does nothing else than spam Demo Bikes to hunt Humvees and Dozers. USA would need very good defense or put Humvee with Hellfire into Chinooks.

**Comment by MTKing4** [comment]
This is good because it buffs the demo's early weakness and nerfs its lategame OPness with the crushed detonation change

**Comment by xezon** [comment]
Pre-Demo Upgrade game is buffed yes. Crushed damage is also a buff, because in 1.04 Demo Terrorist can be crushed without explosion, but in Patch they will explode with weak damage.

**Comment by MTKing4** [comment]
Normalizing demo Terrorist with other terrorists, (or slightly weaker version of that) doesn't read as significant of a buff compared to the significant nerf they're getting for their demo bikes, so overall it's more of a nerf

**Comment by xezon** [comment]
What nerf?

**Comment by MTKing4** [comment]
#2369

**Comment by xezon** [comment]
#2369 was closed.

**Comment by MTKing4** [comment]
I know but my point was that it would mitigate the nerf USA is getting from this change

**Comment by xezon** [comment]
These changes are mutually exclusive.

**Comment by MTKing4** [comment]
Oh, right, don't mind me then

**Comment by xezon** [comment]
Any additional comments on this?

**Pull request merged**
