### PR TITLE
Fix Helix Commandset

### LINKED ISSUE #1513: China Helix Nuke/Napalm Bomb has identical icon for different buttons
China Helix Nuke/Napalm Bomb has identical icon for different buttons.

shot_20221231_111638_1

The Infantry China Helix is the only Helix that shows only one Napalm Icon at a time because its Command Buttons are cramped.

shot_20221231_112144_3

The proper fix is to show a slightly different icon for equipped Helix Bomb.

### PR DESCRIPTION
**Pull request by xezon**
This change was partially reverted with

* #1538

Merge with Rebase.

* ~~Fixes #1513~~

~~This change puts Helix Bomb Upgrade and Helix Bomb Drop buttons on same Command position for all Helix variants.~~ Additionally, Helix Bomb Upgrade is now greyed out while another upgrade is in production.

### No upgrades

shot_20230108_143327_1

### Bomb purchased

shot_20230108_143418_3

### Bomb Upgrade greyed out

shot_20230108_143340_2

### CODE REVIEW

**Comment by ExiLe-ZH** [comment]
This is nice

**Review by ExiLe-ZH — APPROVED** [review]

**Review by Stubbjax — APPROVED** [review]
This is great. The `NOT_QUEUEABLE` is a nice addition as well; that always bugged me.

**Comment by MTKing4** [comment]
I think this adds a new confusion + Problem

The confusion is that i can no longer know if i have the bomb or the upgrade by looking at the icon (i know they have orange and green outlines but it's not very visible, and yes cameo is there but still, less ways to know can be annoying)

The problem is that if i select multiple helixes with 1 having the upgrade i can no longer order a dropping and upgrade Separately

I'm asuming when multiple helixes are selected I'll be forced to buy them all upgrades for the commandset to change to drop, this is a problem

**Comment by xezon** [comment]
The confusion stems from 2 identical icons doing different things. One icon upgrades, the other icon drops bomb. Both look identical and sit right next to each other.

You are correct. With this change applied, Bomb Upgrade and Bomb Drop can no longer be used with shortcut when 2 Helixes have different Command Set active.

Revert this change?

Note that Infantry Helix has identical behavior in original game, due limited command slots.

shot_20230109_205514_2

**Comment by MTKing4** [comment]
> The confusion stems from 2 identical icons doing different things. One icon upgrades, the other icon drops bomb. Both look identical and sit right next to each other.

Yes but the severity of the confusion was less before as you could at least tell you have the upgrade when the upgrade commandset gets a darker tone

I think revert, and stick to the different icon solution, i think a `Red Bomb facing down` icon or `Red Target Crosshair` icon will look nice and quite straight forward and good looking imo

**Comment by MTKing4** [comment]
something like this:

Fun 1

**Comment by xezon** [comment]
I agree with revert, though it is upsetting that it will be inconsistent with Infantry Helix.

**Comment by ExiLe-ZH** [comment]
I'm a simple user, I just tested Inf Lix, the interface, hotkeys and functionality all works perfectly.
 
I don't understand for what reason two buttons is preferred? Or even different icons? That only makes things more inconsistent and cluttered.

**Comment by Stubbjax** [comment]
It is already the case if a player tries to do the same with the Bunker / Gattling Cannon / Speaker Tower upgrades. The same behaviour applies to the Overlord. I disagree that this change adds any meaningful level of confusion at all, and it may even reduce confusion as there is no longer a behavioural difference between Helixes - and further, between upgrades. Standarding the behaviour with the Infantry Helix is a cleaner solution in this case.

However, the inability to drop bombs if Helixes without the upgrade are in the unit selection is a serious problem that needs to be addressed.

**Comment by xezon** [comment]
> However, the inability to drop bombs if Helixes without the upgrade are in the unit selection is a serious problem that needs to be addressed.

This is the culprit of this change. It cuts functionality.

As for the Attachment upgrades, I am trying to fix it, but so far unsuccessfully. It works correctly on Humvees with Drone Upgrades.

**Comment by ExiLe-ZH** [comment]
Ok sorry, I missed that issue. Personally never ever used it with multiple Lixes at the same time in all of my playtime.

An old idea, what about making the upgrade global with all the same parameters as Rocket Pods? :)

**Comment by xezon** [comment]
> An old idea, what about making the upgrade global with all the same parameters as Rocket Pods? :)

This would solve all Command Set design problems.

**Comment by Stubbjax** [comment]
> This is the culprit of this change. It cuts functionality.

If that is the case then I would say revert - we do not want to lose functionality.

> Personally never ever used it with multiple Lixes at the same time in all of my playtime.

This is also my experience, so the impact may be low and the benefits would likely outweigh the drawbacks. But that may change if the upgrade becomes more appealing.

> An old idea, what about making the upgrade global with all the same parameters as Rocket Pods? :)

This would be far too controversial!

**Comment by ExiLe-ZH** [comment]
> This would be far too controversial!

Compared to other controversial changes already in the patch? Lol nah.

It's a nice little improvement for a shitty upgrade noone uses.

**Comment by Stubbjax** [comment]
> > This would be far too controversial!
> 
> Compared to other controversial changes already in the patch? Lol nah.
> 
> It's a nice little improvement for a shitty upgrade noone uses.

What other changes? I think it certainly would be. Especially because there is associated dialogue that would never be heard again.

**Comment by ExiLe-ZH** [comment]
> What other changes?

Seems you missed alot

But I can make another controversial upsetting public topic to see what people think.

**Comment by Stubbjax** [comment]
> > What other changes?
> 
> Seems you missed alot
> 
> But I can make another controversial upsetting public topic to see what people think.

I am interested to know. Probably best to move this discussion to Discord.

**Comment by xezon** [comment]
> Seems you missed alot

This is not a helpful answer to the question. A comparable controversial change was asked for.

I agree with Stubbjax that it would be highly controversial. If my memory is not clouded we have not yet made a change that has changed a unit ability in such a way.

We have report for it here:
* #1014

**Comment by MTKing4** [comment]
I don't recall us merging any controversial change without the majority agreeing to it, that being said, I'd like it if we could agree about adding that bomb upgrade, maybe we can gather public opinion on the matter to see if it's really that controversial

**Pull request merged**
