### PR TITLE
Fix: Demo GLA vehicle suicide disposition issues

### LINKED ISSUE #1696: Demo Suicide hulks spawn with random rotations
Demo Suicide hulks spawn with random rotations.

https://user-images.githubusercontent.com/4720891/218330611-d15f38b4-61a0-4d38-890e-a162856fc41b.mp4

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1696

This change fixes Demo GLA vehicle suicide disposition issues by removing `FlingForce` and `FlingPitch` settings. These settings appear to be intended for infantry units.

### CODE REVIEW

**Review by commy2 — APPROVED** [review]

**Comment by Stubbjax** [comment]
Why does this have the `Patch104p` tag?

**Comment by xezon** [comment]
If i am not mistaken the entire module was newly added by us.

```
; Patch104p @bugfix commy2 29/08/2021 Customize SUICIDED death to resemble regular death module of this vehicle.
```

**Comment by Stubbjax** [comment]
Alright, in that case it's preferable to link to the original PR that introduced the change for context.

**Comment by xezon** [comment]
* #99

I am mistaken. Looks original.

**Pull request merged**
