### PR TITLE
Implement: Missing animation for Secret Service unit

### LINKED ISSUE #2079: AmericaInfantrySecretService missing some animation states
Incomplete implementation in 1.04

Custom map / worldbuilder unit only.

### PR DESCRIPTION
**Pull request by commy2**
- fix https://github.com/TheSuperHackers/GeneralsGamePatch/issues/2079

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/c4ebc147-c2ff-4fa8-a55c-a83b8f8dfd7f

Suitcase disappears while moving, but better than floating above ground I suppose.

### CODE REVIEW

**Comment by xezon** [comment]
Perhaps remove the suit case?

**Comment by commy2** [comment]
Could do, but without suitcase, he's just like CIA Agent:

shot_20230731_230030_1

But without a gun. Making him even more pointless.

**Comment by xezon** [comment]
Ok. Perhaps we can give him animations from Lotus or Hackers? Since they have suitcases?

**Comment by commy2** [comment]
It doesn't work like that:

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/4c3ea9e2-21e7-46ab-8bd4-de1b528c391e

It's either this, making him unmovable (and unkillable?) or nothing.

**Review by xezon — APPROVED** [review]

**Pull request merged**
