### PR TITLE
Dummy weapons no longer deal damage, triggering *UnderAttack EVA events

### PR DESCRIPTION
**Pull request by xamorish**
Dummy weapons no longer trigger EVA *UnderAttack events while keeping their initial purpose.

### CODE REVIEW

**Comment by commy2** [comment]
Conflicts with some of my future unit AI tweaks. I suggest we wait on this and then compare it with my solution.

**Comment by xamorish** [comment]
> 
> 
> Conflicts with some of my future unit AI tweaks. I suggest we wait on this and then compare it with my solution.

Sure! Optionally, if your AI tweaks aren't being merged anytime soon, this PR could be somehow labeled for later review to prevent forgetting about it.

**Comment by commy2** [comment]
"ongoing discussion" serves that purpose.

**Comment by xezon** [comment]
I added new tag :)

**Comment by xezon** [comment]
@xamorish 
commy2 closed it because his change attempts to fix the same issue. Your changes look a bit different. Your change touches more files. Could you please check if commy2's change covers everything necessary?

**Comment by xezon** [comment]
commy2:
> My fix is superior as it

> 1) affects more units, e.g. Outpost and Bus (EVA message would play before rocket guys hit)
> 2) also removes the impact effect, which this PR does not

> Must say that only affecting NEUTRALS is clever though.

**Pull request closed without merging**
