### PR TITLE
Move unedited W3D files into GameFilesOriginalZH folder

### PR DESCRIPTION
**Pull request by xezon**

### CODE REVIEW

**Comment by commy2** [comment]
> BIN -25.6 KB
[Patch104pZH/GameFilesEdited/Art/W3D/ABSDILink_L.W3D](https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1038/files#diff-db5c17c44cb4f15009b70820820fea170221fd9ccd64f579c1d984ded2f13b0d)

This should stay.

**Comment by xezon** [comment]
I was wondering about it. It is unchanged to original. What does it do?

**Comment by commy2** [comment]
Ah, I am wrong.
ABSDILink_L.W3D = original animated particle cannon explosion beams 
ABSWGLink_L.W3D = hex edited using purple texture for SWG
ABLGCLink_L.W3D = hex edited using red texture for Laser Cannon

ABSDILink_L.W3D was added, because you requested I add the original reference. 
The file is unchanged from original. Your call where it goes or if we delete it.

**Comment by xezon** [comment]
It already is in the other folder, that is why it does not show as moved, but deleted. I will create new Repo (Private) with all reference files and clean this Repo. Maybe I should do that straight away and not even bother moving files.

**Review by commy2 — APPROVED** [review]

**Pull request closed without merging**
