### PR TITLE
Change: Improve tool tip text of China Internet Center

### PR DESCRIPTION
**Pull request by xezon**
This change improves the tool tip text of the China Internet Center from

> Helps hackers bring in money. Can be upgraded to spy on opponents

to

> Protects Hackers and helps them bring in money faster. Can be upgraded to spy on opponents

for US, DE, FR, ES, IT, BP, PL, RU.

### CODE REVIEW

**Comment by ExiLe-ZH** [comment]
> This change improves the tool tip text of the China Internet Center from
> 
> 
> 
> > Helps hackers bring in money. Can be upgraded to spy on opponents
> 
> 
> 
> to
> 
> 
> 
> > Protects Hackers and helps them bring in money faster. Can be upgraded to spy on opponents
> 
> 
> 
> for US, DE, FR, ES, IT, BP, PL, RU.

Would it be helpful if it's more specific like so?

"Protects Hackers and helps them hack and gain experience 20% faster. Can be upgraded to spy on opponents."

**Comment by MTKing4** [comment]
I like it like this 
> Protects Hackers and helps them bring in money faster. Can be upgraded to spy on opponents. Can Survive a direct hit from Super Weapons

**Comment by commy2** [comment]
"Protects Hackers and helps them hack ~~and gain experience~~ 20% faster. Can be upgraded to spy on opponents."

Redundant, possibly misleading. They hack faster, therefore gain experience faster.

**Comment by MTKing4** [comment]
Yeah that's better 

> Protects Hackers and helps them hack 20% faster. Can be upgraded to spy on opponents. Can Survive a direct hit from Super Weapons

**Comment by xezon** [comment]
Documentation added. Looks good.

**Comment by ExiLe-ZH** [comment]
Think it would good to use commie's final suggestion, the 20% isn't really documented anywhere.

**Comment by MTKing4** [comment]
> Think it would good to use commie's final suggestion, the 20% isn't really documented anywhere.

I agree, Also think it would be good to say that it can survive direct Superweapon hits

**Comment by commy2** [comment]
Should mention the 20%. Explains what it does and indirectly documents our buff to non Inf.

**Comment by ExiLe-ZH** [comment]
> > @MTKing4 Protects Hackers and helps them hack 20% faster. Can be upgraded to spy on opponents. Can Survive a direct hit from Super Weapons

This is perfect.

**Pull request merged**
