### PR TITLE
Change: Improve voice setup of USA Paladin Tank

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Relates to #176

This change adds 1 former unused sound to the USA Paladin Tank and swaps other sounds.

### PaladinTankVoiceSelect

* ~~vpalsed "Polished and Ready"~~ **(Optional)**
* vpalseg "Preserving freedom" **(Optional)**
* vpalatf "Protecting our people"

### PaladinTankVoiceCreate

* ~~vpalseg "Preserving freedom"~~ **(Optional)**
* vpalsed "Polished and Ready" **(Optional)**

### CODE REVIEW

**Comment by MTKing4** [comment]
You're changing the voice upon creation and adding it to selection? I don't like that, it would confuse players, I'd rather have the same setup as it is now

**Comment by ExiLe-ZH** [comment]
I mean you get used to it fast enough, think 'polished and ready' makes sense when rolling out of the factory. But why remove it from select?

**Comment by xezon** [comment]
Creation voice change demoted to optional bundle pack.

**Comment by xezon** [comment]
"Polished and Ready" really only makes sense as creation sound. Having it for selection is odd because the Paladin could be badly damaged at that time.

**Comment by xezon** [comment]
Documentation added. Looks good.

**Pull request merged**
