### PR TITLE
Change: Remove PointDefenseLaser from USA Airforce Carpet Bomber

### LINKED ISSUE #926: AFG B2 Bomber Has PDL When Calling Carpet Bombing But Not When Calling MOAB
This is a strange difference between the two.

I don't think either should have a PDL.

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #926

This change removes the PointDefenseLaser from the USA Airforce Carpet Bomber.

# Rationale

All other USA Airforce General Promotion planes have no PointDefenseLaser, including the B52 bomber that delivers the MOAB and looks identical to the B52 Carpet Bomber.

USA Airforce General does not need this PointDefenseLaser on it to be useful either. ~~The USA Airforce Carpet Bomber has the lowest cooldown timer (2:30) of all faction carpet bombers.~~ It flies much faster than China Carpet Bombers. And it is available from Rank 1 unlike China Carpet Bombers at Rank 3.

USA Airforce opponents will now be able to shoot down the Carpet Bomber more easily with Rockets.

### CODE REVIEW

**Comment by commy2** [comment]
> The USA Airforce Carpet Bomber has the lowest cooldown timer (2:30) of all faction carpet bombers and it is available from Rank 1.

The AFG Carpet Bomber has the highest recharge time at 4:00, with Nuke Carpet being 3:00 and vChina/Inf/Tank Carpet being 2:30.

The tooltip is just wrong in 1.04.

**Comment by commy2** [comment]
Another way to fix this would've been to replace the `Transport` token in ObjectCreationList AirF_SUPERWEAPON_CarpetBomb:
"AirF_AmericaJetB3" with "AmericaJetB3". Then the PDL Bomber version could be kept for custom maps or something.

**Comment by xezon** [comment]
Done. Tested. Worked.

**Comment by Jundiyy** [comment]
All good. And I was about to say what commy said. Would be nice to keep the original for mappers.

**Comment by RisingZH** [comment]
Should fix the issue of afg carpet dropping bombs before reaching the targeted location.

**Comment by ExiLe-ZH** [comment]
> Should fix the issue of afg carpet dropping bombs before reaching the targeted location.

https://github.com/TheSuperHackers/GeneralsGamePatch/issues/925#issuecomment-1218887340

**Comment by Jundiyy** [comment]
> Done. Tested. Worked.

I presume you mean commy's method? If so, I'd prefer this way.

**Review by commy2 — APPROVED** [review]

**Pull request merged**
