### PR TITLE
Change: Cancel Construction command button border color from Blue to Yellow

### PR DESCRIPTION
**Pull request by xezon**
This changes Cancel Construction command button border color from Blue to Yellow.

🟦 Blue = BUILD
🟩 Green = ACTION
🟧 Orange = UPGRADE
🟨 Yellow = SYSTEM

The Yellow border color matches better the color scheme of similar buttons, such as Yellow STOP button for units, and Yellow SELL button for structures.

## Patched

shot_20230120_232357_2

### CODE REVIEW

**Comment by xezon** [comment]
Any opinions on this?

**Comment by commy2** [comment]
Looks weird for some reason. "Stop" here has a different meaning (cancel construction) than "Stop" on units (stop moving/firing), so they don't necessarily have to use the same colour I suppose.

**Comment by Stubbjax** [comment]
> Looks weird for some reason. "Stop" here has a different meaning (cancel construction) than "Stop" on units (stop moving/firing), so they don't necessarily have to use the same colour I suppose.

I was going to say, one could also argue that the blue border distinguishes the Cancel Build command as a separate function from the Stop command. As far as players are concerned, all construction-related command borders are blue. Since Cancel Build is a construction-related command, the current colour scheme makes sense in its current state and requires no change.

**Comment by xezon** [comment]
> Since Cancel Build is a construction-related command, the current colour scheme makes sense in its current state and requires no change.

Wouldn't the same principle then apply for Structure Sell Command too? Sell is Yellow.

**Comment by Stubbjax** [comment]
> > Since Cancel Build is a construction-related command, the current colour scheme makes sense in its current state and requires no change.
> 
> Wouldn't the same principle then apply for Structure Sell Command too? Sell is Yellow.

Perhaps, but this is the way it has always been. Selling isn't technically construction-related, despite the in-game mechanic appearing as such. Intuitively, people don't associate selling with construction. At least I don't expect my house to be bulldozed when I sell it.

**Comment by MTKing4** [comment]
I think it looks fine as yellow and it makes sense, both stop commands are literally the same icon and everything, so why would they have different borders? The stop building argument doesn't make much of a sense really, since sell is actually building related according to the game logic and is yellow, so this one should be yellow just like other stop buttons

**Comment by commy2** [comment]
> both stop commands are literally the same icon and everything, so why would they have different borders

Because they do different things.

**Comment by xezon** [comment]
If they do different things, then they should not be the same icon.

**Comment by commy2** [comment]
Invent _time machine_ and tell EALA about it.

**Comment by penfriendz** [comment]
Well we can make a new button image right?

**Comment by MTKing4** [comment]
I wouldn't like creating a new image, current image is discriptive and clear as it is, also it's very _Iconic_ (see what i did there? ^^ ) and people like the current icon very much

**Pull request closed without merging**
