### PR TITLE
Change: Streamline key mappings of China Mines upgrades

### PR DESCRIPTION
**Pull request by xezon**
* Relates to #2095

This change streamlines the key mappings of China Mines upgrades. This makes it a bit easier to learn and operate. Optional bundle only.

## Original

| Language   | Land Mines key | Neutron Mines key |
|------------|----------------|-------------------|
| US         | L              | M                 |
| DE         | L              | M                 |
| FR         | M              | M                 |
| ES         | M              | M                 |
| IT         | M              | M                 |
| KO         | L              | M                 |
| ZH         | L              | M                 |
| BP         | M              | M                 |
| PL         | M              | M                 |

## Patched (Optional)

| Language   | Land Mines key | Neutron Mines key |
|------------|----------------|-------------------|
| US         | M              | M                 |
| DE         | M              | M                 |
| FR         | M              | M                 |
| ES         | M              | M                 |
| IT         | M              | M                 |
| KO         | M              | M                 |
| ZH         | M              | M                 |
| BP         | M              | M                 |
| PL         | M              | M                 |

### CODE REVIEW

**Comment by xezon** [comment]
Not clear to me if this is desired. But the L, M key mapping looks silly.

**Comment by xezon** [comment]
The least we can do is put this in Optional bundle, so that new players can have better key mapping here.

**Comment by MTKing4** [comment]
i think it's better to give them separate keys, L for Land mines and M for Neutron

also what happens if you select buildings with different mines?? can't upgrade either?

**Comment by commy2** [comment]
You can only ever select 1 building at once, so no multi select issues on buildings.

**Comment by MTKing4** [comment]
Ah yeah true.

Still, I'm used to the L key for mines and i wouldn't wanna change it

**Comment by xezon** [comment]
I will demote this to Optional bundle.

**Comment by xezon** [comment]
Demoted to Optional bundle.

**Comment by xezon** [comment]
Documentation added. Works.

**Pull request merged**
