### PR TITLE
Change: Reduce particle count of AmericaJetCargoPlane_SupplyDropZone

### PR DESCRIPTION
**Pull request by xezon**
This change removes the black smoke trails from all 4 propellers on Supply Drop Zone plane. Only the contrails on the wing tips remain. This will render it a bit cheaper.

### CODE REVIEW

**Comment by commy2** [comment]
Is this necessary? Is there a tangible benefit?

**Comment by ExiLe-ZH** [comment]
Idk, I really like those visuals. Is it really worth to sacrifice visual quality for the performance gain?

**Comment by commy2** [comment]
Same ^
Supply Plane doesn't seem so bad compared to Hackers. And the +$20 spam from BMs is also done with particles, and that happens all the time, not every 2 minutes.

**Comment by xezon** [comment]
Did you test it? The particle trails behind the propellors are faint. I was unable to observe a noticable visual degradation with these removed. Removing these 4 particles saves 4 particles per plane, or 40 for 10 planes. I would expect this to give some performance gain, because nothing is cost free. Do you need this measured?

**Comment by xezon** [comment]
Other USA cargo planes also have propeller smoke.

**Pull request closed without merging**
