### PR TITLE
Add temporary Patch104p text in main menu

### LINKED ISSUE #155: Add WIP text to Main Menu
Add WIP text to Main Menu.
Can say something like "Patch104p: Work In Progress. For test purposes only."
Can be big and ugly. This will help communicate that any test versions we release is for test purposes only.

### PR DESCRIPTION
**Pull request by xezon**
closes #155

### CODE REVIEW

**Comment by commy2** [comment]
Is it possible to instead use an image?

**Comment by xezon** [comment]
Do you mean changing the background texture? Yes possible. But not sure if better. Would be more difficult to change text. Here its simple text edit. So can be changed and removed easily anytime.

**Comment by commy2** [comment]
> Would be more difficult to change text.

True.

I guess it won't look as bad once STR/CSF files are there.

**Comment by xezon** [comment]
shot_20211013_214810_1

**Comment by commy2** [comment]
Missing: This looks very professional
Hate the font though.

**Comment by xezon** [comment]
It's Arial Bold.

**Comment by commy2** [comment]
That's funny. Exactly what I use at work. The aliasing is looks off. Has the font black outlines? It clashes with the black / semi-transparent dark grey backdrop.

Maybe it's just JPG being JPG.

**Comment by xezon** [comment]
Yes it has a black drop shadow.

**Comment by commy2** [comment]
Looks much better now:

<details><summary>Screenshot</summary>

title

</details>

**Review by commy2 — APPROVED** [review]
lgt my wnd untrained eyes

**Pull request merged**
