### PR TITLE
Fix: Tank Muzzle Flash effects

### PR DESCRIPTION
**Pull request by xezon**
This change fixes Tank Muzzle Flash effects and texture.

* SmokePuff texture artifacts fixed
* Muzzle Flare fade out fixed
* Muzzle Smoke direction and size fixed

## Original

https://user-images.githubusercontent.com/4720891/188817976-50244189-1659-4268-a380-73e6c9d16977.mp4

## Patched

https://user-images.githubusercontent.com/4720891/188818022-1a7d9d09-b452-4870-a905-93453131126b.mp4

### CODE REVIEW

**Comment by ExiLe-ZH** [comment]
probably is more realistic, you can see some smoke come from the barrels irl:

https://youtu.be/was2xsfFgQ0?t=21

Although it's mostly up kicking dust, is there not such effect ingame to use?

edit: Hmmm original muzzle flash itself seems bigger/brighter/longer lasting? Not sure if this part is an improvement.

**Comment by xezon** [comment]
To improve smoke visual, I now made puff a bit brighter and shifted slight magenta tint to orange tint. This should blend more graciously with Muzzle Flame.

Tested on snow, grass and desert. Looks good.

shot_20220907_122306_1

**Comment by commy2** [comment]
This looks very nice and indeed similar to what a real life cannon would look like after firing.
Did you come up with this yourself or is this taken from a mod?

**Comment by xezon** [comment]
I reduced `TankMuttleFlashSmoke` life time from 50 to 40 frames, because the smoke lingers too long with 50. The `TankSmallMuttleFlashSmoke` lasts 30 frames. The Nuke Cannon and Battleship smoke remains 50. That looks good to me.

**Comment by Stubbjax** [comment]
Can we get some video footage of the additional tweaks? I'm not a fan of the strong contrast between the flash and smoke in the original footage.

image

**Comment by xezon** [comment]
The image in https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1149#issuecomment-1239207184 shows latest edit.

Note that particles from first video are Original color, so they cannot be complained against.

**Comment by xezon** [comment]
Any further opinions on this?

**Comment by xezon** [comment]
> Did you come up with this yourself or is this taken from a mod?

I tweaked it from scratch after I noticed that the Battle Master puff flies downwards.

**Comment by xezon** [comment]
Is this change good?

**Comment by xezon** [comment]
Reviewed. The new smoke puff was a bit too bright. Fixed. New smoke puff texture was used on unrelated effects. Reverted. This change now touches Tank effects only.

Tested on Snow, Gras, Desert, Shell Map. Looks good to me.

**Pull request merged**
