### PR TITLE
Fix: English audio restoration for icia (3)

### PR DESCRIPTION
**Pull request by xezon**
* Follow up for #1061

This change fixes crackling, fade in, fade out for icia sounds. It uses 406 kB uncompressed.

The sounds are bundled into the following archives:
* OptionalAudioArabic
* OptionalAudioBrazilian
* OptionalAudioChinese
* OptionalAudioEnglish
* OptionalAudioItalian
* OptionalAudioKorean
* OptionalAudioPolish
* OptionalAudioSpanish

### CODE REVIEW

**Comment by MTKing4** [comment]
There's arabic audio? :O

**Comment by commy2** [comment]
No. It says Arabic will use the restored (English) sound files.

**Comment by MTKing4** [comment]
Oh ok

**Comment by xezon** [comment]
Sounds good to me.

**Pull request merged**
