### PR TITLE
Change: Add missile exhaust and lens flare particles to guided missiles of USA Missile Defender

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Closes #1551

This change adds missile exhaust and lens flare particles to guided missiles of USA Missile Defender. To accommodate both regular white and heroic red rocket exhausts, the laser beam and flare colors are adjusted for improved contrast of effects.

https://user-images.githubusercontent.com/4720891/212485273-a4e51fa7-3f06-43cf-a89f-30141876b2a3.mp4

### CODE REVIEW

**Review by Stubbjax — APPROVED** [review]
I think the missile trails look good with the Laser Lock. The red glow certainly looks much nicer, though could maybe do with some additional refinement, like adding a white glow to the tip of the launcher as well. I'm not sure if the darkened laser helps with visibility.

Here is ShockWave's effect for reference:

image

**Comment by xezon** [comment]
How about this?

https://user-images.githubusercontent.com/4720891/212770028-e481066e-3e3a-497b-a092-e2bcf939dd20.mp4

**Comment by ExiLe-ZH** [comment]
Looks very good

**Comment by MTKing4** [comment]
Looks good, now you're making it hard for us to choose between this and the no trail one 😄

**Comment by xezon** [comment]
Just added a tiny bit of transparency to the red flare so it does not look as strong in group.

It's a real looker for sure.

shot_20230117_001320_3

**Comment by commy2** [comment]
What about performance? These shoot fast and come in big groups, and all scenarios in which they laser lock are critical for micro.

**Comment by xezon** [comment]
> What about performance? These shoot fast and come in big groups, and all scenarios in which they laser lock are critical for micro.

I expect it to be not more costly than big blobs of Rocket Humvees shooting on enemy targets, which we know works okay.

**Comment by xezon** [comment]
I think the bright core of the flare is a bit too large.

**Comment by xezon** [comment]
Flare optimized to fit laser beam better.

https://user-images.githubusercontent.com/4720891/218260492-5a16e3bd-b438-4ad2-9c6a-05f91cec88bb.mp4

**Comment by Stubbjax** [comment]
Here's a direct comparison of the laser flares for clarity:

image

**Comment by xezon** [comment]
Documentation added. Looks good.

**Comment by ExiLe-ZH** [comment]
> Here's a direct comparison of the laser flares for clarity:
> 
> image

Comparing it directly I actually do miss the light rays in the new red one, can that be readded? Think it looks good.

**Pull request merged**
