### PR TITLE
Fix: Point Defense Laser of USA Paladin no longer attacks dead infantry

### LINKED ISSUE #2070: USA Paladin's PointDefenseLaserUpdate does not target new infantry after a kill reliably
The USA Paladin's PointDefenseLaserUpdate does not target new infantry units after a kill reliably. It takes several seconds before shooting again for no apparent reason. When not killing a target, then it has no problem switching targets.

```
  Behavior = PointDefenseLaserUpdate ModuleTag_07
    WeaponTemplate        = PaladinPointDefenseLaser
    PrimaryTargetTypes    = BALLISTIC_MISSILE SMALL_MISSILE
    SecondaryTargetTypes  = INFANTRY
    ScanRate              = 500
    ScanRange             = 120.0
    PredictTargetVelocityFactor = 3.0
  End
```

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/3d51ba70-6c95-4ee1-9367-fec5ad5058b4

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #2070
* Follow up for #75

With this change the Point Defense Laser of the USA Paladin no longer attacks dead infantry.

### CODE REVIEW

**Comment by MTKing4** [comment]
Next to fix: USA Paladin no longer T-bags dead infantry

**Review by commy2 — APPROVED** [review]
lets hope it doesn't break something else

**Comment by xezon** [comment]
If it does then we will find it. Not worried about it.

**Comment by xezon** [comment]
Documentation updated. Looks good.

**Pull request merged**
