### PR TITLE
Fix: Nuke Cannon Shell Detonation Effect Has Offset

### PR DESCRIPTION
**Pull request by commy2**
Spawns effect via dummy, which should not suffer impressions.

### CODE REVIEW

**Review by xezon — DISMISSED** [review]
Looks good to me.

**Comment by xezon** [comment]
This change does not work correctly when targeting unit instead of terrain. Same for both weapons.

https://user-images.githubusercontent.com/4720891/188618957-5a2a2c14-e4a3-4967-973c-929dbf83595f.mp4

**Comment by commy2** [comment]
Good catch. Dumb game. Should work now. Note to self: Don't test nuke explosion effects on Nuke Battlemasters.

**Review by xezon — APPROVED** [review]
Looks good now.

**Comment by xezon** [comment]
Good to merge?

**Pull request merged**
