### PR TITLE
Change: Fix and improve the look of China Mine explosion effects

### PR DESCRIPTION
**Pull request by xezon**
This change improves the look of Mine explosion effects.

## Original

Red mines spawn small white flares. Fade out is not smooth.
Purple neutron mines spawn huge yellow flares. Flare lasts shorter than red flare.

https://user-images.githubusercontent.com/4720891/188329576-4a8310d7-1b43-40a3-be36-f8f9a58177a6.mp4

## Patched

Red mines spawn small red flares. Fade out is smooth.
Purple neutron mines spawn medium purple flares. Flare lasts same time as red flare.

Effects for Neutron Nuke Cannon and EMP Mines remains unchanged.

https://user-images.githubusercontent.com/4720891/188329580-4fbba241-fc43-494b-bd67-fa7d30876344.mp4

### CODE REVIEW

**Comment by commy2** [comment]
A bit too purple? Looks like the Scrin are invading again.

**Comment by xezon** [comment]
It is the same color as the mines. Do you think it should be a bit brighter?

**Comment by commy2** [comment]
More blue and white, less red.

**Comment by ExiLe-ZH** [comment]
Original Neutron a LOT better, new one looks too slow, small and weak and color reminds more of a toxin cloud.

New red one is kinda fine too though.

Maybe this could improve animation:
- Same overall animation length.
- Faster initial explosion (expansion part), makes it look powerful I think.
- Longer smoother fadeout. 
- Keep neutron size.
- Neutron color more white blue'ish instead of yellow.

**Comment by commy2** [comment]
The OG Neutron always seemed to me like the game is glitching out. It doesn't even look like Nuke Cannon Neutron does. Maybe some inspiration can be found from that (including sound).

**Comment by xezon** [comment]
* Red Mine & Neutron Mine flash time reduced from 15 to 10 frames
* Neutron mine flash size increased from 20 to 30
* Neutron mine flash color more bright and blue

https://user-images.githubusercontent.com/4720891/188398107-7d9a28d4-df5a-4866-a2a7-8795c493039a.mp4

**Comment by commy2** [comment]
I strongly prefer the original mine effect for Landmines. I don't see why the explosion has to be red just because the mines themselves glow red. Red explosions make me think of Demogen and his TNT clouds (tank shells, suicide, Bomb Truck, Scud Launcher, Scud Storm etc.)

The Neutron mine explosion is indeed whack and should be fixed. Why not make that one closer to what the Nuke Cannon Neutron Shell looks like and call it a day?

**Comment by MTKing4** [comment]
I kinda agree with commy

Red Explosion = Demo
Purple Explosion = Gamma

Maybe just fix the particles with no color change.

**Comment by commy2** [comment]
Yeah, goes without saying that particle bug fixes are very much appreciated. But changing colors are "sideways" changes, if you understand what I'm saying, and not direct improvements, and therefore a matter of taste.

**Comment by xezon** [comment]
What about this version?

* Same colors as per original
* Neutron Flash is smaller than original
* Fixed glitches

https://user-images.githubusercontent.com/4720891/210636420-a250f6f9-e400-446b-bc51-e822291b5da9.mp4

**Comment by MTKing4** [comment]
This looks good

**Comment by xezon** [comment]
Good. Shall we go with it?

**Comment by MTKing4** [comment]
Yes for me

**Comment by ExiLe-ZH** [comment]
Last video looks pretty good, neutron explosion is pretty big still, is what I like. 

I'm also curious what a white flash would look like with neutrons.

**Comment by Stubbjax** [comment]
> What about this version?
> 
>     * Same colors as per original
> 
>     * Neutron Flash is smaller than original
> 
>     * Fixed glitches

I feel like the flare colours should match or at least be swapped. It's more obvious when you compare side by side:

image

Otherwise I think the size reduction on the neutron mines while keeping the original distinction / feeling is a definite improvement.

**Comment by xezon** [comment]
I don't like the Original colors either. But to me it read as if the others want to keep original colors.

**Comment by ExiLe-ZH** [comment]
It's just that the first version overdid it a little, like the purple flash looked really toxic or alien-like and the red kinda too "demo'ish".

**Comment by xezon** [comment]
In the first version I matched flare colors with actual mine colors.

**Comment by ExiLe-ZH** [comment]
Long story short, I agree with Stubjax, last version looks very good, just swap the colors and it's perfect.

**Comment by xezon** [comment]
Documentation added. White flash effect re-added to Neutron explosion. Looks good.

**Pull request merged**
