### PR TITLE
Tweak: Paradrop Rangers and Missile Defenders in batches

### PR DESCRIPTION
**Pull request by commy2**
* Follow up for #2026
* Follow up for #2056

With this change, the Rangers and Missile Defenders are created in batches of 5, because all Rangers, then all MDs looks strange to me.

### CODE REVIEW

**Comment by xezon** [comment]
What about this one? #2057

**Comment by commy2** [comment]
Alzheimers. I don't remember that.

Although spawning 1-1-1-1-1-1 is equally strange looking. Can we agree on 2-2-1 -- 2-2-1 or something instead?

**Comment by xezon** [comment]
The disadvantage of opening 10000 Pulls :D

Yeah not sure what pattern is best here.

**Comment by commy2** [comment]
(3-2) times n is pretty straight forward. Paradrop 1 is just first unit type, then second unit type; Paradrop 2 and 3 are just multiples of that.

**Comment by xezon** [comment]
Do you prefer 3-2-3-2 over 1-1-1-1-1-1-1-1-1 ?

**Comment by commy2** [comment]
Yes, definitely. 1-1-1-1-1 is just as bad as all-rest

**Review by xezon — APPROVED** [review]
Ok.

**Comment by xezon** [comment]
I like more mix better.

**Pull request merged**
