### PR TITLE
Fix: ChinaInfantryOfficer poison death effects

### PR DESCRIPTION
**Pull request by xezon**
This change fixes ChinaInfantryOfficer poison death effects.

### CODE REVIEW

**Comment by xezon** [comment]
Untested. Just found by coincidence when searching for OCL's.

**Review by Stubbjax — APPROVED** [review]

**Comment by xezon** [comment]
This change should be tested once before merge.

**Comment by xezon** [comment]
Poison death does not look proper. Looks broken on various misc infantry units.

**Comment by xezon** [comment]
This change is superseeded by #2074

**Pull request closed without merging**
