### PR TITLE
Fix: avthunderbolt texture issues

### PR DESCRIPTION
**Pull request by xezon**
This change fixes and improves textures of USA Microwave Tank.

### avthunderbold

* Fixes inconsistent wheel positions between damaged states
* Fixes misaligned bolts
* Fixes missing gaps in metal plates
* Fixes top plate layout near top vents
* Adds small vents on black rectangles of front top plate
* Removes burns on microwave door

### avthunderbold_d, avthunderbold_d1

* Fixes inconsistent wheel positions between damaged states
* Fixes misaligned bolts
* Fixes missing gaps in metal plates
* Fixes top plate layout near top vents
* Adds small vents on black rectangles of front top plate
* Improves burn texture transitions at the chassis sides
* Replaces all bullet holes with dust and burns
* Repaints lazy burns

## Original

shot_20220923_085350_1

## Patched

shot_20220923_093912_1

## Original

shot_20220923_085419_2

## Patched

shot_20220923_093928_2

### CODE REVIEW

**Comment by Stubbjax** [comment]
Do you intend to fix the inconsistencies with the dead state?

**Comment by xezon** [comment]
That will be for W3D fix pass. Right now I am just doing Texture pass.

**Comment by xezon** [comment]
I have spotted a few more issues. Some bolts were misplaced. And gaps on some metal plates were missing. Fixed. Looks okay now.

**Comment by xezon** [comment]
I am happy with it.

shot_20221119_204845_2

**Pull request merged**
