### PR TITLE
Change: Removed duplicate fields from various civilian / system objects.

### PR DESCRIPTION
**Pull request by Stubbjax**
The former field is completely overridden.

### CODE REVIEW

**Comment by xezon** [comment]
Do any flags of the duplicate field make any sense for the respective objects?

**Comment by Stubbjax** [comment]
> Do any flags of the duplicate field make any sense for the respective objects?

It's basically a question whether `CAN_SEE_THROUGH_STRUCTURE` should apply to any of the following objects:

image

**Comment by xezon** [comment]
CAN_SEE_THROUGH_STRUCTURE renders the silhouette through object? How are comparable structures setup?

**Comment by Stubbjax** [comment]
> CAN_SEE_THROUGH_STRUCTURE renders the silhouette through object? How are comparable structures setup?

It allows units to shoot through them.

**Comment by xezon** [comment]
I have no preference. Could make sense that unit can shoot over than fountain. If in doubt, keep original behavior.

**Comment by Stubbjax** [comment]
> I have no preference. Could make sense that unit can shoot over than fountain. If in doubt, keep original behavior.

It's funny that you can blow it up. Only then are you allowed to shoot over it. It seems reasonable to adjust this one.

https://user-images.githubusercontent.com/11547761/200130870-234102c0-a0c0-4ffc-8d4a-468c5c3365e1.mp4

**Comment by xezon** [comment]
I suggest commit these 2 changes individually, to keep it separate. I created task for the CAN_SEE_THROUGH_STRUCTURE.

* #1446

**Review by xezon — APPROVED** [review]

**Pull request merged**
