### PR TITLE
Tweak usa drone shroud range

### LINKED ISSUE #983: USA Scout and Hellfire drone have astonishing Cloud Clearing Range, Battle Drone does not
USA Scout and Hellfire drone have astonishing Cloud Clearing Range, Battle Drone does not.

| Object                           | Shroud Clearing Range | Area       |
|----------------------------------|-----------------------|-----------:|
| Original USA Sentry Drone        | 350                   | 384845     |
| Original USA Scout Drone         | 500 (+75+10 wander)   | min 785398 |
| Original USA Battle Drone        | 150 (+75+10 wander)   | 70685      |
| Original USA Hellfire Drone      | 500 (+75+10 wander)   | min 785398 |
| Original USA Humvee              | 320                   | 321699     |
| Original USA Missile Defender    | 400                   | 502654     |
| Original China Outpost           | 500                   | 785398     |
| Original China Lotus             | 400                   | 502654     |

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #983

This change increases ShroudClearingRange of USA Battle Drone from 150 to 300 and decreases it of USA Hellfire Drone from 500 to 400.

| Object                           | Attack Range | Shroud Clearing Range | Area   | Adv. over Battle | Adv. over Hellfire |
|----------------------------------|--------------|-----------------------|--------|------------------|--------------------|
| Original USA Battle Drone        |              | 150 (+75+10 wander)   | 70685  |                  |                    |
| Original USA Hellfire Drone      | 150          | 500 (+75+10 wander)   | 785398 | +1011%           |                    |
| Original USA Scout Drone         | 110          | 500 (+75+10 wander)   | 785398 | +1011%           | +0%                |
| Patched USA Battle Drone (this)  |              | 300 (+75+10 wander)   | 282743 |                  |                    |
| Patched USA Hellfire Drone (this)| 150          | 400 (+75+10 wander)   | 502654 | +77%             |                    |
| Patched USA Scout Drone (this)   | 110          | 500 (+75+10 wander)   | 785398 | +177%            | +56%               |

## Other objects for reference

| Object                           | Shroud Clearing Range | Area       |
|----------------------------------|-----------------------|-----------:|
| Original USA Sentry Drone        | 350                   | 384845     |
| Original USA Humvee              | 320                   | 321699     |
| Original USA Missile Defender    | 400                   | 502654     |
| Original China Outpost           | 500                   | 785398     |
| Original China Lotus             | 400                   | 502654     |

## Rationale

The original Hellfire drone has a massive sight of 500 matching the Scout Drone. It costs 5 times as much as the Scout Drone, but it also has a good weapon and much more armor. The original Battle drone has a useless sight of just 150. Since most USA Tanks have a sight of 300, the Battle drone sight adds nothing in practice.

With the readjusted shroud ranges the Scout drone retains its pristine range of 500, while the Hellfire is reduced a little bit, but can still see much more than all USA vehicles by a large margin. The range was not reduced further because it is the most expensive drone and it is a much less consequential change to tweak the range just as much as this change does. Meanwhile the Battle Drone now sees as far as most USA Tanks, and since it sways around its host vehicle, it will increase the shroud range just a bit while it sways. For most practical purposes, the Battle drone will not provide a tangible gain in shroud range.

The new ranges offer a more logical distribution of shroud clearing ranges and make the Scout Drone more unique with its very large shroud range. Since the Scout Drone just costs 100, it is always easily accessible and a USA player can afford one to benefit of its perks.

| Object                           | Perks                                      |
|----------------------------------|--------------------------------------------|
| Patched USA Battle Drone (this)  | Machine Gun, Good Armor, Repair ability    |
| Patched USA Hellfire Drone (this)| Best Weapon, Best Armor, Good Shroud Range |
| Patched USA Scout Drone (this)   | Stealth Detection, Best Shroud Range       |

# Media

## Original Battle Drone

original_battle

## Original Hellfire Drone

original_hellfire

## original Scout Drone

original_scout

## Patched Battle Drone

patched_battle

## Patched Hellfire Drone

patched_hellfire

### CODE REVIEW

**Comment by commy2** [comment]
Please also change SupW_AmericaVehiclePointDefenseDrone for consistency. It is essentially a Battle Drone, but with PDL.

**Comment by ExiLe-ZH** [comment]
Edit: didn't expand the whole post on my phone.

I'm still questioning the rationale for 400 though, is it just the price? 

Wouldn't it be better if players have to mix different drones? Because besides stealth detection I don't see the need to spam anything else than Hellfires.

Btw, I think we should also look into scout drone price, atm it is very spammable, which might make Vee spam more expensive however very usefull for distracting fire from Quads and Gatling Tanks (though this will be fixed with patch yes?).

**Comment by xezon** [comment]
More drastic range reduction would be more controversial and I am not willing to do that with this change. I adjusted the Rationale text accordingly.

**Comment by ExiLe-ZH** [comment]
> More drastic range reduction would be more controversial and I am not willing to do that with this change. I adjusted the Rationale text accordingly.

Fair enough.

**Comment by xezon** [comment]
SupW_AmericaVehiclePointDefenseDrone adjusted.

**Pull request closed without merging**
