### PR TITLE
Fix: Cash Bounty does not mention Command Center requirement in General's promotion menu

### PR DESCRIPTION
**Pull request by commy2**
shot_20230820_110959_1

This line disappears if the player owns a Command Center.

### CODE REVIEW

**Comment by xezon** [comment]
What happens when player has Cash Bounty 1, builds Command Center, sells Command Center, then looks at Cash Bounty 2. Will the given information be correct? Will player need another Command Center after selecting Cash Bounty 2?

**Comment by commy2** [comment]
The text will show that you require a Command Center.

You do in fact require a Command Center to upgrade Bounty from 1 to 2 or 2 to 3:

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/0f2924a3-d49c-429f-98a1-5d395a4a4cb2

**Review by xezon — APPROVED** [review]
Nice.

**Comment by kABUSE1** [comment]
Are we sure that we want this behaviour at all?

It would be more logical if you only receive cash bounty if you own a command center when scoring the kill.

**Comment by xezon** [comment]
It is a legitimate question. The current design is odd. Ideally it would either be fully passive always or always require the Command Center.

Is there any other Generals Power that acts like Cash Bounty does?

**Comment by commy2** [comment]
> Is there any other Generals Power that acts like Cash Bounty does?

I can't think of any. I don't think there is.

**Comment by xezon** [comment]
How about we just remove this requirement altogether? Just make it a passive ability always? The advantage of that would be that it would not require learning this odd requirement. And it is also close to the Original where it just requires dropping a 0% scaffold briefly.

**Comment by commy2** [comment]
I suppose CashBounty module could be added to Default/Object.ini:DefaultThingTemplate. That way, any object can handle the cash bounty logic.

Pretty much every other General's Power is used by the Command Center though. Exceptions are unit unlocks and unit veterancy, and the AFG Carpet Bomber. The ideal would be if the power just turned off if no Command Center is left as kABUSE1 suggested. But even in that case, this "Requires: Command Center" line makes sense.

**Comment by xezon** [comment]
It would be a quite big design change if the Cash Bounty was no longer a purely passive reward. Design wise it would be much better if it was bound to DefaultThingTemplate or Command Center. The current implementation is a bit confusing.

**Comment by kABUSE1** [comment]
Agree, quite a big change.

Scaffold cc makes no sense. I only see two valid options:
1. Make it fully passive
2. Make it require a fully constructed, alive CC at all times (no hole)

I think option 2 is okay, as cash bounty is currently very, very powerful. Might as-well delay it a bit.

**Comment by xezon** [comment]
We already changed it in Patch to this #595. It means full Command Center is required, but Cash Bounty level will remain active even if Command Center is demolished. The extra confusing part then starts when selecting a new Cash Bounty level, because then a new Command Center is required.

**Comment by commy2** [comment]
Here's a patch where Command Center is no longer requried at all: https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2263

**Comment by MTKing4** [comment]
I don't think this is a good idea, we're buffing GLAs unnecessarily

I'd much rather having Cash Bounty only work when there's a CC up, and not work otherwise 

Also we're adding a huge favoritism over an already highly favored genpower, people will now pick cash bounty over the other options even more than before because it's the only genpower that doesn't require a CC and can get its value instantly, in a meta where GLA builds CCs very late and or often times forgotten, with a change like this, CC will likely not be built until level 5

**Comment by xezon** [comment]
> I don't think this is a good idea, we're buffing GLAs unnecessarily

It is not a buff. Not even controversial. It just removes the useless mechanic of placing a temporary scaffold to activate it.

> I'd much rather having Cash Bounty only work when there's a CC up, and not work otherwise

This would be a definite nerf and controversial.

**Comment by MTKing4** [comment]
Maybe not a direct buff, but buff nonetheless because it increases the chances of a player getting cash for kills, for example when you reach level 3 but don't have extra cash for CC, you can benefit from cash bounty regardless, and much earlier than before, in 1.04 that was not possible

> This would be a definite nerf and controversial.

True, We could make it at least require 1 CC built after getting the promotion then it's unlocked for good even after upgrades, I'm fine with that as well

**Comment by xezon** [comment]
> Maybe not a direct buff, but buff nonetheless because it increases the chances of a player getting cash for kills, for example when you reach level 3 but don't have extra cash for CC, you can benefit from cash bounty regardless, and much earlier than before, in 1.04 that was not possible

Ok this makes sense. Then buff and controversial labels need to be added.

**Comment by xezon** [comment]
Cash Bounty is a really good upgrade, because it incentives the player to pick fights, instead of just sit back and do nothing. So in a way we would like it to remain an attractive option, as it should make the game better for it.

**Pull request merged**
