### PR TITLE
Change: Reduce LAN Countdown From 5 To 3 Seconds

### PR DESCRIPTION
**Pull request by commy2**
shot_20221016_104211_2

gogogogo

### CODE REVIEW

**Comment by xezon** [comment]
gogogogoogooogooo xD

**Comment by xezon** [comment]
The issue report we had for this was closed.
* #461

**Comment by Jundiyy** [comment]
Yes please.

**Comment by xezon** [comment]
We should test this in a Network room with a few players to check that nothing odd happens.

**Comment by MTKing4** [comment]
i can test this now if anyone's up

**Comment by xezon** [comment]
Works. Game runs normal.

shot_20221030_164128_3

**Review by xezon — APPROVED** [review]

**Pull request merged**
