### PR TITLE
Fix: Remove wheel from chassis of Overlord Tank

### PR DESCRIPTION
**Pull request by xezon**
This change removes the wheel(s) on the chassis of Overlord Tank. The fix is very minor, thus can be optional content.

## Original

shot_20220920_123822_1

## Patched (Optional)

shot_20220920_124048_1

### CODE REVIEW

**Comment by xezon** [comment]
Added before and after image.

**Comment by commy2** [comment]
No need to make this one optional. This just seems like an error and direct improvment without any redesigns.

**Comment by xezon** [comment]
Are you sure? It is such marginal fix, it is not strictly necessary to package in core. The 5 textures will cost 214 kb uncompressed, 128 kb 7z compressed.

**Comment by Jundiyy** [comment]
Yea, don't think anyone will say anything. Just that one wheel thing that visible? And the one on the other side.

**Comment by xezon** [comment]
On the Gattling Turret too.

**Comment by Jundiyy** [comment]
Ah yea, didn't look there. If it costs too much kb then leave it.

**Comment by commy2** [comment]
I am not concerned about size right now. But I am unsure about just how many textures will be replaced, so maybe I have the wrong expectation.

**Comment by xezon** [comment]
There will be more optional texture fixes like this. Basically anything that is not really a bug, but an enhancement, just like this one. The Scorpion texture fix in comparison is much more severe, because it literally looks different in stages. I will change the label of this one.

**Comment by commy2** [comment]
I honestly cannot tell if this is a bug or just dust up. What is this wheel supposed to be? Seems like an unwrapping error.

**Comment by xezon** [comment]
Hard to say what the intention was. It is the same kind of circle that is used for the wheels. It is baked into the texture, so no model error.

**Comment by commy2** [comment]
Copy paste for the wheels and this was a floating layer meant to be hidden?

**Comment by xezon** [comment]
Possible.

**Comment by xezon** [comment]
Is this good to go?

**Comment by alanblack166** [comment]
Not a fix, as that "wheel" is depicted in the original concept art:
13921011_970803903018544_3825368905647755300_n

**Comment by xezon** [comment]
In that case we can probably change the optic a bit to not look identical to the tread wheels. I will take a look.

**Comment by xezon** [comment]
I modified the side circle to look like some sort of vent. This should blend it a bit more gently then the tread wheel.

shot_20220920_192728_1

**Comment by xezon** [comment]
Fixed and Pushed for all variants.

**Review by commy2 — APPROVED** [review]

**Pull request merged**
