### PR TITLE
Add test map for all factions UPDATE

### PR DESCRIPTION
**Pull request by MTKing4**
Fixed:
+ Toxin Command Center Missing
+ Added All Generals Challenge Command Centers
+ added flags in front of Generals Challenge CCs to distinguish from the vanilla ones

### CODE REVIEW

**Comment by xezon** [comment]
There are conflicts that you need to resolve. I assume you did not merge xezon/GeneralsGamePatch:main into your fork main.

**Comment by MTKing4** [comment]
i can't seem to be able to merge automatically

**Comment by xezon** [comment]
You can merge in your fork main.

**Comment by xezon** [comment]
Something is not right. This PR now shows ini file changes !?

**Pull request closed without merging**
