### PR TITLE
Change: Increase GLA Bomb Truck Bio Bomb range bonuses by +25%, +30% and stack Bio Bomb + High Explosive range bonuses to +45%, +54%

### LINKED ISSUE #800: GLA Bomb Truck Bio Bomb upgrade does not grant any practical benefit
> commy2: 
> It does make the Bomb Truck spawn a medium sized poison cloud which does 2.0 damage over time or 2.5 damage over time with Anthrax Beta upgrade. Anthrax Gamma does nothing.
> 
> What doesn't change is the initial explosion damage. That is always 1000, with or without Bio Bomb and without or without any Anthrax upgrade.

### Proposal 1
Remove upgrade all together, give tox by default.

### Proposal 2
Remove upgrade and reintegrate into Beta/Gamma, purchasing this will upgrade the Bombtrucks instead.

### Proposal 3
Buff damage output (that justifies $500)

### Proposal 4
Nerf HE and buff Biobomb, rebalance prices accordingly so that cost/performance is same as before.

### Proposal 5
Make Biobomb cheap.

### LINKED ISSUE #944: Demo GLA Bomb Truck deals same damage as regular Bomb Truck
Demo GLA Bomb Truck deals same damage as regular Bomb Truck. Is this an unexpected problem?

```
;------------------------------------------------------------------------------
;The basic explosive damage inflicted to nearby units when detonated.
;------------------------------------------------------------------------------
Weapon BombTruckDefaultBombDamage
  PrimaryDamage = 1000.0
  PrimaryDamageRadius = 40.0
  SecondaryDamage = 100.0
  SecondaryDamageRadius = 65.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 99999.0
  ProjectileObject = NONE
  DamageDealtAtSelfPosition = Yes   ; this is a suicide bomber... remember?
  RadiusDamageAffects = SELF ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 0
  ClipSize = 1
  ClipReloadTime = 0
  AutoReloadsClip = No
  ;**** DON'T USE ANY EFFECTS!!! ****
End

;------------------------------------------------------------------------------
;A larger explosive damage inflicted immediately to nearby units if the
;bomb-truck has the high-explosive upgrade.
;------------------------------------------------------------------------------
Weapon BombTruckHighExplosionBombDamage
  PrimaryDamage = 2000.0
  PrimaryDamageRadius = 50.0
  SecondaryDamage = 200.0
  SecondaryDamageRadius = 85.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  ProjectileObject = NONE
  RadiusDamageAffects = SELF ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 0                   ; time between shots, msec
  ClipSize = 1                            ; how many shots in a Clip (0 == infinite)
  ClipReloadTime = 0                      ; how long to reload a Clip, msec
  AutoReloadsClip = No

  AntiGround = Yes
  DamageDealtAtSelfPosition = Yes
  WeaponBonus = PLAYER_UPGRADE DAMAGE 125%
  ;**** DON'T USE ANY EFFECTS!!! ****
End

;------------------------------------------------------------------------------
;DEMO GENERAL VARIATION
;The basic explosive damage inflicted to nearby units when detonated.
;------------------------------------------------------------------------------
Weapon Demo_BombTruckDefaultBombDamage
  PrimaryDamage = 1000.0
  PrimaryDamageRadius = 40.0
  SecondaryDamage = 100.0
  SecondaryDamageRadius = 65.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 99999.0
  ProjectileObject = NONE
  DamageDealtAtSelfPosition = Yes   ; this is a suicide bomber... remember?
  RadiusDamageAffects = SELF ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 0
  ClipSize = 1
  ClipReloadTime = 0
  AutoReloadsClip = No
  ;**** DON'T USE ANY EFFECTS!!! ****
End

;------------------------------------------------------------------------------
;DEMO GENERAL VARIATION
;A larger explosive damage inflicted immediately to nearby units if the
;bomb-truck has the high-explosive upgrade.
;------------------------------------------------------------------------------
Weapon Demo_BombTruckHighExplosionBombDamage
  PrimaryDamage = 2000.0
  PrimaryDamageRadius = 50.0
  SecondaryDamage = 200.0
  SecondaryDamageRadius = 85.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  ProjectileObject = NONE
  RadiusDamageAffects = SELF ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 0                   ; time between shots, msec
  ClipSize = 1                            ; how many shots in a Clip (0 == infinite)
  ClipReloadTime = 0                      ; how long to reload a Clip, msec
  AutoReloadsClip = No

  AntiGround = Yes
  DamageDealtAtSelfPosition = Yes
  WeaponBonus = PLAYER_UPGRADE DAMAGE 125%
  ;**** DON'T USE ANY EFFECTS!!! ****
End
```

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #944
* Fixes #800

This change reduces the cost of Bio Bomb upgrade, consolidates the range bonus with High Explosive Upgrade, and stacks them if both upgrades are installed on host vehicle. The effective primary and secondary damages remain the same.

This change in turn rewards Bio Bomb and Bio Bomb + High Explosives with more damage range, which can inflict damage to more things in area and therefore increase effectiveness of Truck attack.

Additionally Demo High Explosive bonus range is matched with Regular Bio Bomb + High Explosive, which in turn makes the Demo High Explosive upgrade more valuable for the same price as the the regular High Explosive upgrade.

A fully upgraded Bomb Truck will cost 1900, as opposed to 2200 before. It can be used once only.

HE = High Explosive
BB = Bio Bomb

| Upgrade                | Price | Damage       | Primary Range | Secondary Range | Perks        |
|------------------------|------:|-------------:|--------------:|----------------:|--------------|
| Original HE            | 500   | +100%        | +25%          | +30%            |              |
| Original BB            | 500   | +0%          | 0%            | +0%             | Toxin Puddle |
| Patched BB (this)      | 200   | +0%          | +25%          | +30%            | Toxin Puddle |
| Original HE + BB       | 1000  | +100%        | +25%          | +30%            | Toxin Puddle |
| Patched HE + BB (this) | 700   | +100%        | +45%          | +54%            | Toxin Puddle |
| Original Demo HE       | 500   | +100%        | +25%          | +30%            |              |
| Patched Demo HE (this) | 500   | +100%        | +45%          | +54%            |              |

Bomb Truck buff list in a nutshell:
* 300 cheaper BB upgrade
* More range with BB upgrade
* More range with HE + BB upgrade

# Stats

Default Primary damage is 1000. Upgraded 2000.
Default Secondary damage is 100. Upgraded 200.

Primary damages are unchanged. HE Bomb Truck is very good at destroying buildings. Adding 500 extra damage to Bio Bomb and stacking it with High Explosive would be non consequential against most structures, but would allow 1 Bio Bomb Truck to destroy AmericaStrategyCenter, 3 upgraded Bomb Trucks to destroy Command Center and 3 fully upgraded Bomb Trucks to deal 90% damage to Superweapons. Armor setup of Superweapons shields Bomb Truck damage well.

| Structure                   | Health | HE Truck count | Regular Truck count | Caused damage |
|-----------------------------|-------:|---------------:|---------------------|---------------|
| GLAPalace                   | 3000   | 1              |                     | 66%           |
| AmericaStrategyCenter       | 1500   |                | 1                   | 66%           |
| ChinaPropagandaCenter       | 1000   | 1              |                     | 100%          |
| AmericaWarFactory           | 2000   | 1              | 2                   | 100%          |
| ChinaWarFactory             | 2000   | 1              | 2                   | 100%          |
| GLAArmsDealer               | 2000   | 1              | 2                   | 100%          |
| ChinaNuclearMissileLauncher | 4000   | 2              | 4                   | 80%           |
| GLAScudStorm                | 4000   | 2              | 4                   | 80%           |
| AmericaParticleCannonUplink | 4000   | 2              | 4                   | 80%           |
| GLACommandCenter            | 5000   | 3              | 6                   | 96%           |
| AmericaCommandCenter        | 5000   | 3              | 6                   | 96%           |
| ChinaCommandCenter          | 5000   | 3              | 6                   | 96%           |
| ChinaSupplyCenter           | 2000   |                | 1                   | 100%          |
| AmericaSupplyCenter         | 2000   |                | 1                   | 100%          |
| GLASupplyStash              | 2000   |                | 1                   | 100%          |
| AmericaSupplyDropZone       | 1000   |                | 1                   | 100%          |
| GLABlackMarket              | 1000   |                | 1                   | 100%          |

The Primary damage is an overkill for most vehicles. 1000 damage will deal 90% damage to regular Overlord. The secondary damage is strong enough to critically injure infantry. 100 damage will deal 90% damage to soldiers. 200 damage will kill infantry, and also light vehicles. Veteran and upgraded vehicle will suffer less damage accordingly.

| Vehicle                   | HE Truck count | Caused secondary damage |
|---------------------------|---------------:|------------------------:|
| GLAVehicleRocketBuggy     | 1              | 100%                    |
| GLAVehicleTechnical       | 1              | 100%                    |
| GLAVehicleToxinTruck      | 1              |  80%                    |
| GLAVehicleQuadCannon      | 1              |  70%                    |
| GLATankScorpion           | 1              |  60%                    |
| AmericaVehicleTomahawk    | 1              | 100%                    |
| AmericaVehicleHumvee      | 1              |  85%                    |
| AmericaTankAvenger        | 1              |  70%                    |
| AmericaLaserTank          | 1              |  40%                    |
| AmericaTankCrusader       | 1              |  40%                    |
| AmericaTankMicrowave      | 1              |  40%                    |
| ChinaVehicleInfernoCannon | 1              | 100%                    |
| ChinaTankECM              | 1              |  80%                    |
| ChinaTankDragon           | 1              |  80%                    |
| ChinaTankGattling         | 1              |  70%                    |
| ChinaTankBattlemaster     | 1              |  50%                    |
| ChinaTankOverlord         | 1              |  20%                    |

# Rationale

Original Bio Bomb is expensive and only gives the Toxin Puddle perk. The puddle kills infantry in a radius of 80 for 30 seconds - if it would walk over it. It is useless for most practical needs in late game, because toxin puddles can be removed with force fire to the ground or simply not be stepped on with soldiers and other units.

The increased damage radius gives the Bio Bomb a boost in effective damage area, +56% over Default and +112% over Default in combination with High Explosive. This is double area damage boost. ~~However, practically Bomb Truck is mostly concerned about damage in front of it, as there typically will be no enemy units behind a Bomb Truck where it just passed through. Therefore, practically the Bomb Truck does not benefit from area damage bonus as much as a projectile such as a SCUD Missile would. We therefore are mostly counting on a +25% over Default range increase, and in combination with High Explosive bomb a +50% over Default or +20% over High Explosion range increase.~~

| Primary Radius | Area    | Area increase over 40 | Area increase over 50 |
|----------------|--------:|----------------------:|----------------------:|
| 40             | 5026    |                       |                       |
| 50             | 7854    | +56%                  |                       |
| 58 (this)      | ~ 10682 | ~ +112%               | ~ +36%                |
| 60             | 11310   | +125%                 | +44%                  |

| Secondary Radius | Area    | Area increase over 65 | Area increase over 85 |
|------------------|--------:|----------------------:|----------------------:|
| 65               | 13273   |                       |                       |
| 85               | 22698   | +71%                  |                       |
| 100 (this)       | ~ 32123 | ~ +142%               | ~ +41.5%              |
| 105              | 34636   | +160%                 | +52%                  |

The increased range does make the unit more competitive. It fits well within ranges of comparable weapons.

| Weapon                                                     | PrimaryDamageRadius | SecondaryDamageRadius |
|------------------------------------------------------------|--------------------:|----------------------:|
| Original SCUDLauncherGunExplosive                          | 50                  | 100                   |
| Original NukeCannonGun                                     | 50                  | 60                    |
| Original SupW_FuelBombDetonationWeapon                     | 70                  |                       |
| Original SuicideDynamitePack                               | 18                  | 50                    |
| Original SuicideBikeBomb                                   | 20                  | 50                    |
| Original BombTruckBioBombDamage                            | 40                  | 65                    |
| Original BombTruckHighExplosionBioBombDamage (HE)          | 50                  | 85                    |
| Patched BombTruckBioBombDamage (BB) (this)                 | 50                  | 85                    |
| Patched BombTruckHighExplosionBioBombDamage (HE+BB) (this) | 58                  | 100                   |

| Weapon                                                     | PrimaryDamage | SecondaryDamage |
|------------------------------------------------------------|--------------:|----------------:|
| Original SCUDLauncherGunExplosive                          | 300           | 50              |
| Original NukeCannonGun                                     | 400           | 50              |
| Original SupW_FuelBombDetonationWeapon                     | 300           |                 |
| Original SuicideDynamitePack                               | 500           | 300             |
| Original SuicideBikeBomb                                   | 700           | 10              |
| Original BombTruckBioBombDamage                            | 1000          | 100             |
| Original BombTruckHighExplosionBioBombDamage (HE)          | 2000          | 200             |
| Patched BombTruckBioBombDamage (BB) (this)                 | 1000          | 100             |
| Patched BombTruckHighExplosionBioBombDamage (HE+BB) (this) | 2000          | 200             |

Most ground units have an attack range of 150 or more, so are certainly able to stop an approaching Bomb Truck. It's new secondary damage range of max 105 will give Bomb Truck a better chance to deal some damage to enemy units.

The reduced price from 500 to 200 is reasonable, because the High Explosive upgrade costs 500 and gives a much more valuable bonus with +100% damage.

Bio Bomb is now worth the investment, as it gives an effective range bonus, both alone and in combination with the High Explosive upgrade.

If the ranges turn out to be too powerful in practice, then they can be reduced a bit.

## Could it be too powerful?

Unlikely. Unlike Demo Bike, Bomb Truck is not spammable in swarms. It will kill all allied units nearby and almost kill nearby friendly Bomb Trucks. In practice only one at a time can be sent to reduce risk of total loss. Additionally it has a long build time of 15 and will essentially block production for other units that could be of more use.

Bomb Truck also requires Palace, meaning it is not usable in early game. By that time, an opposing USA could already have Strategy Center and Humvees with +20% range bonus, China could have ECM Tanks, Lotus and GLA could have Rocket Buggies to stop incoming Bomb Trucks.

A Bomb Truck remains a risky investment that may not pay off at all.

# Media

## Default, Bio Bomb, High Explosive, HE Bio

The Bio HE Shockwave is a bit to bright, it was tweaked already but was not captured in this video.

bomb_truck_expl_bio

https://user-images.githubusercontent.com/4720891/186246517-7c772866-d6eb-4aac-bfef-453304b39567.mp4

## Default, Anthrax Bomb, High Explosive, HE Anthrax

bomb_truck_expl_anthrax

https://user-images.githubusercontent.com/4720891/186247023-4d28f075-00ee-4660-8923-bae3709ba966.mp4

## Default, Gamma Bomb, Demo Default, Demo High Explosive

Note the trucks are parked a bit closer to the enemy vehicles, so the Demo HE Truck actually killed a lot more.

The Gamma Shockwave is a bit to bright, and pink, it was tweaked already but was not captured in this video.

bomb_truck_expl_gamma

https://user-images.githubusercontent.com/4720891/186253796-4fb15b80-87dc-4753-9ad1-11ed4c9063bb.mp4

### CODE REVIEW

**Comment by ExiLe-ZH** [comment]
Really professional study, awesome work.

But I indeed have some concerns or rather questions about the new primary range and changes in general.

1. You stated BB upgrade has no consequences vs Structures, but is this true? The +25% simply means that the BT is 25% harder to stop right? Because if the BT gets stopped 25% further away, then it still deals the same damage as if it were closer? I'm not saying this is a bad thing, just want to know the facts.

2. Secondary range stat for patched BB is missing, since stacked is +60%, then BB value alone is +30%?

I'd like to see how it works in practice, someone today can test this with me?

**Comment by xezon** [comment]
Missing stat added. The section about buildings was mainly about damages. As for range, a Truck could damage more buildings in theory, however it is unlikely in practical terms, because structures are typically large and the range will not be sufficient to reach many of them. The range buff is most consequential for approaching enemy targets and having a better probability to hit them when Truck is killed.

**Comment by Stubbjax** [comment]
Will the explosion particle effects need some adjustment with the increased range?

**Comment by xezon** [comment]
> Will the explosion particle effects need some adjustment with the increased range?

I will check.

**Comment by Jundiyy** [comment]
Looks good. Nice job 👌

**Comment by ExiLe-ZH** [comment]
I had another interesting SAFE idea in mind for the gamepatch, what about splitting damage and range? 
- HE upgrades damage output only, will be 40% cheaper than in 1.04.
- Biobomb increases range only, will be 60% cheaper than in 1.04 (could be a viable it's own when used vs low armored vehicles and/or infantry).
- Demo HE upgrades both damage and range, will be 40% cheaper (however misses the Toxin Puddle).

Overall it's a very safe change, there's only a very tiny performance difference (5% extra range), investing in both upgrades costs the same as HE alone in 1.04 ($1500) and the Toxin Puddle is basically added for free.

Upgrade | Price | Damage | Primary Range | Secondary Range | Perks
-- | -- | -- | -- | -- | --
HE | 500 | +100% | +25% | +30% |  
HE (patched)  | 300 | +100% | +0% | +0% | 
BB | 500 | +0% | +0% | +0% | Toxin   Puddle
BB (patched) | 200 | +0% | +30% | +30% | Toxin Puddle
HE + BB | 1000 | +100% | +25% | +30% | Toxin   Puddle
HE + BB (patched) | 500 | +100% | +30% | +30% | Toxin Puddle
Demo HE | 500 | +100% | +25% | +30% |  
Demo HE (patched) | 300 | +100% | +30% | +30% | 

It's easy to understand for the user and the tooltips can described in a very simplistic fashion:
- **HE:** upgrades damage by 100%.
- **Biobomb:** Increases the damage radius by 30% and contaminates the area with toxins.
- **Demo HE:** Upgrades damage by 100% and damage radius by 30%.

**Comment by xezon** [comment]
The issue I take with 300 HE price is that it looks cheap. It basically gives a second Bomb Truck by doubling the damage. And a second Bomb Truck would cost 1200. Other than that it is not yet clear to me what the best ranges are. 105 max looks good on paper and in testing so far. It is just slightly above SCUD Launcher damage area. On that note though, 100 secondary range for SCUD Missile is quite astonishing, even if it just applies 50 damage. Having multiple SCUD Launchers easily stacks it.

**Comment by ExiLe-ZH** [comment]
> The issue I take with 300 HE price is that it looks cheap. It basically gives a second Bomb Truck by doubling the damage. And a second Bomb Truck would cost 1200. Other than that it is not yet clear to me what the best ranges are. 105 max looks good on paper and in testing so far. It is just slightly above SCUD Launcher damage area. On that note though, 100 secondary range for SCUD Missile is quite astonishing, even if it just applies 50 damage. Having multiple SCUD Launchers easily stacks it.

Does look cheap indeed, could also substract $100 from the base vehicle itself and re-add it to the upgrade.

Whatever we do, I would like to see a use case for each state of the vehicle, non-upgraded, BB only, HE only, BB+HE. Makes it more fun and interesting than no-brainer upgrades.

And I do like your proposal of the overall increased radius, vs Scud performance it doesn't look too imbalanced on paper, with the fact that only the radius in front of the vehicle is the only dangerzone in practice usually. For a $1900 investment, the new performance is probably justified.

**Comment by ExiLe-ZH** [comment]
Another proposal, which is a slight alteration of the main proposal (in the main post). That's removing the secondary range bonus from HE and readd it to the BB (so that will be 60%). Then there's a more distinct use case for each upgrade, where HE is used vs structures, BB vs units.

Optionally we could also look into the base vehicle vs upgrade prices. For example we can make the Biobomb $300 ($200 also sounds super cheap, especially with the idea above) and make the base vehicle $100 cheaper. This could create more use cases for the non-upgraded base vehicle aswell.

**Comment by xezon** [comment]
I appended further improvements. Max PrimaryDamageRange was reduced from 60 to 58 and max SecondaryDamageRange from 105 to 100. It now matches SCUD Launcher missile. The calculations for new numbers are updated in first post. Also videos and images have been added. All particles have been optimized to match the Bomb Truck damages better. Originally they just had some different colors, but no different sizes.

From my side this now looks acceptable. Whether or not Bomb Truck is too good because of this we would need to see in practice. Note: Unlike Demo Bike, Bomb Truck is not spammable in swarms. It will kill all allied units nearby and almost kill nearby friendly Bomb Trucks. In practice only one at a time can be sent. However, if multiple Trucks do reach their target then the explosion can be strong enough to erase the world and nearby universes.

**Comment by ExiLe-ZH** [comment]
Sounds good!

About friendly fire (and I mentioned this idea a couple of times already actually), it could be a tool to balance out DB's (if they just did friendly fire to other DB's), this way Demo can't just sent unstoppable big blobs.

**Comment by MTKing4** [comment]
This is getting to complicated, what are we going to type in patch notes?

**Bomb truck Goes Boom better now**

**Comment by xezon** [comment]
Basically it was upgraded from useless to slightly useless :-)

**Pull request closed without merging**
