### PR TITLE
Change: Increase armor of China Internet Center against Aurora bomb by 30%

### PR DESCRIPTION
**Pull request by xezon**
* Follow up for #1989
* Relates to #223
* Relates to #754

This change increase the armor of the China Internet Center against the Aurora bomb by 30%.

The Internet Center becomes more difficult to take down with Aurora bombers.

| Structure                          | No. Auroras to kill | No. Alpha Auroras to kill |
|------------------------------------|---------------------|---------------------------|
| China Propaganda Center            |  1                  |  1                        |
| China Airfield                     |  2                  |  1                        |
| China War Factory                  |  2                  |  2                        |
| China Command Center               |  5                  |  3                        |
| Original Internet Center           |  3                  |  2 (Hackers alive)        |
| **Patched Internet Center (this)** |  4                  |  3 (Hackers dead)         |

## Original Damages

| Weapon                                | Internet Center Damage | Hackers killed       |
|---------------------------------------|------------------------|----------------------|
| **USA Alpha Aurora**                  | 58%                    | No                   |
| **USA Aurora**                        | 40%                    | No                   |

## Patched Damages

| Weapon                                | Internet Center Damage | Hackers killed       |
|---------------------------------------|------------------------|----------------------|
| USA Carpet Bomb + Lvl 2 A10           | 100%                   | Yes                  |
| USA Lvl 1 Spectre + Lvl 2 A10         | 100%                   | Yes                  |
| USA Lvl 2 Spectre + Lvl 1 A10         | 100%                   | No                   |
| GLA Demo Scud Storm                   | 100%                   | No                   |
| GLA Lvl 3 Demo Rebel Ambush           | 100%                   | No                   |
| USA Lvl 3 Spectre                     | 99%                    | No                   |
| USA Carpet Bomb + Lvl 1 Spectre       | 99%                    | No                   |
| China Carpet Bomb + Lvl 2 Artillery   | 98%                    | No                   |
| Patched GLA Anthrax Gamma Scud Storm  | 92%                    | No                   |
| GLA Scud Storm                        | 92%                    | No                   |
| USA Lvl 3 A10                         | 90%                    | No                   |
| China Nuke Missile                    | 85%                    | No                   |
| USA Particle Cannon                   | 85%                    | No                   |
| USA Carpet Bomb + Lvl 1 A10           | 79%                    | No                   |
| USA Lvl 1 Spectre + Lvl 1 A10         | 77%                    | No                   |
| China Lvl 3 Artillery                 | 76%                    | No                   |
| USA Lvl 2 Spectre                     | 72%                    | No                   |
| USA Lvl 2 A10                         | 61%                    | No                   |
| China Lvl 2 Artillery                 | 51%                    | No                   |
| China Carpet Bomb                     | 48%                    | No                   |
| USA Carpet Bomb                       | 48%                    | No                   |
| USA Lvl 1 Spectre                     | 47%                    | No                   |
| **USA Alpha Aurora (This)**           | **47%**                | **No**               |
| USA Fuel Bomb                         | 40%                    | No                   |
| USA MOAB                              | 40%                    | No                   |
| USA Lvl 1 A10                         | 31%                    | No                   |
| **USA Aurora (This)**                 | **29%**                | **No**               |
| China Lvl 1 Artillery                 | 26%                    | No                   |

# Rationale

China Hackers are typically vulnerable when out in the open and are easy to kill with most weapons. The Internet Center is the only safe refuge for China Hackers, but it can be built just once and accommodate a maximum of 8 Hackers only. It costs 7500 to build the Internet Center and the 8 Hackers.

This change gives China better chances to protect 8 valuable Hackers in late game to secure a life line while the majority of China's Hackers will remain vulnerable out in the open. Enemy players now need to combine more weapons and strikes to take out the Internet Center and its Hackers.

### CODE REVIEW

**Comment by MTKing4** [comment]
Just one important thing to keep in mind
The spectre from `USA Lvl 1 Spectre + Lvl 2 A10` is the Level 5 Spectre right? Not the level 3 one from SWG and AIR

Because if so that's good that you won't be able to kill it before level 5 for laser and USA, but what about AIR and SWG spectres? Remember They shoot for 10 seconds instead of 15

Clearly Air is still superior, being the only subfaction that can kill IC from level 3 genpowers, do you guys think this is ok?

**Comment by xezon** [comment]
USA Lvl 1 Spectre is the Level 1 Spectre of Airforce General.

**Comment by MTKing4** [comment]
Ok so any spectre with lvl2 A10 would do the job, and USA Airforce has two combo options from level 3 and SWG has one option in Level 3. USA and laser won't til level 5

China will forever be afraid of the Mighty Airforce General

**Comment by xezon** [comment]
Anything else to add here? I would like proceed with this.

**Comment by ExiLe-ZH** [comment]
I think final changes are balanced

**Comment by MTKing4** [comment]
I personally don't like that only Airforce and SWG can take out IC with two combo-ed genpowers from level 3, it means that chinas will still suffer vs Airforce in particular, is there nothing that can be done about this?

**Comment by xezon** [comment]
This change is only about Aurora damages. It does not change the others.

As for General Powers, all USA and all China can use Combo Powers to kill Internet Center. China Trails a bit behind however, but that is because the Artillery Barrage is relatively weak, not because the Internet Center is too strong.

**Comment by MTKing4** [comment]
Oh yeah, in that case you can relay my message to the IC hp buff pull

As for this one, 4 auroras to kill IC is fine, but maybe it's better if they don't kill the hackers? So that 1 airfield worth of Auroras can't nullify china economy and USA needs to add another airfield for one more aurora

but I'm not too sure about this, 4 auroras are $10K worth + airfield which is already too much, so maybe this setup is fine already

**Comment by MTKing4** [comment]
> As for General Powers, all USA and all China can use Combo Powers to kill Internet Center. China Trails a bit behind however, but that is because the Artillery Barrage is relatively weak, not because the Internet Center is too strong.

I'm aware of that, but that wasn't my point, my point is that only Airforce and SWG can kill IC AND Hackers with only 2 genpowers right from level 3, and Airforce actually have 2 Options for it (Carpet + lvl2 A10, Spectre+ lvl2 A10) which is highly advantageous over other factions and is very early to be able to kill all china's IC + hackers

Basically it will be like nothing has changed for air and SWG because they can still kill IC + Hackers the same way they always have and with ease

**Comment by xezon** [comment]
> I'm aware of that, but that wasn't my point, my point is that only Airforce and SWG can kill IC AND Hackers with only 2 genpowers right from level 3, and Airforce actually have 2 Options for it (Carpet + lvl2 A10, Spectre+ lvl2 A10) which is highly advantageous over other factions and is very early to be able to kill all china's IC + hackers

Yes USA has best Powers for killing things.

> Basically it will be like nothing has changed for air and SWG because they can still kill IC + Hackers the same way they always have and with ease

It has changed because all Generals Powers will deal less damage and 1 Particle Cannon is no longer enough to kill the pristine Internet Center. So China is definitely better off.

> As for this one, 4 auroras to kill IC is fine, but maybe it's better if they don't kill the hackers? So that 1 airfield worth of Auroras can't nullify china economy and USA needs to add another airfield for one more aurora

4 Auroras will not kill the Hackers. But 3 Alpha Auroras will. USA can also combine Aurora with Powers. So for example 1 Aurora + Level 2 Spectre will kill pristine Internet Center and all Hackers.

**Comment by ExiLe-ZH** [comment]
Keep in mind that active repairing can make a difference aswell, not all powers can be re-aimed to target the dozer.

**Comment by MTKing4** [comment]
> Yes USA has best Powers for killing things.

Not any USA, laser and vanilla cannot, only after lvl5

> It has changed because all Generals Powers will deal less damage and 1 Particle Cannon is no longer enough to kill the pristine Internet Center. So China is definitely better off.

You're not addressing my point, I'm talking about air and SWG only, they can still kill it fully right from level3
I'm using the table you put above, is that outdated or something?

## Patched Damages

| Weapon                                | Internet Center Damage | Hackers killed       |
|---------------------------------------|------------------------|----------------------|
| USA Carpet Bomb + Lvl 2 A10           | 100%                   | Yes                  |
| USA Lvl 1 Spectre + Lvl 2 A10         | 100%                   | Yes

Air and SWG can obtain the above combination from level 3, while other USAs only obtain it after level 5, which is a big deal

> 4 Auroras will not kill the Hackers. But 3 Alpha Auroras will. USA can also combine Aurora with Powers. So for example 1 Aurora + Level 2 Spectre will kill pristine Internet Center and all Hackers.

I don't understand, your table above says that they do?

| Structure                          | No. Auroras to kill | No. Alpha Auroras to kill |
|------------------------------------|---------------------|---------------------------|
| **Patched Internet Center (this)** |  4                  |  3 (Hackers dead)         |

> Keep in mind that active repairing can make a difference aswell, not all powers can be re-aimed to target the dozer.

Spectre definitely could, which both Air and SWG have from level 3

**Comment by xezon** [comment]
> You're not addressing my point, I'm talking about air and SWG only, they can still kill it fully right from level3. I'm using the table you put above, is that outdated or something?

It is not outdated. It is not clear to me what you need. The goal was that no single Superweapon and Power can take out the pristine Internet Center and all the Hackers inside. This goal was achieved. That there are strike combinations that still can kill it is the way it originally was as well.

**Comment by MTKing4** [comment]
I understand that, I'm just trying to compare all the different combos available for each faction and how fair they are, and by that table, hackers inside are still vulnerable vs air and SWG pretty Early, which means the particle nerf won't even matter because it comes up much later than level 3 powers for air and SWG, and that is unfair, if you disagree with this and think it's fine for air and swg to always be able to nullify hackers that early, then I'll make a sperate issue for this and go into more detail into how bad this is for balance

For reference to other genpowers, a balanced approach for `USA Carpet Bomb + Lvl 2 A10` and `USA Lvl 1 Spectre + Lvl 2 A10` is if they killed the IC only, and hackers survive, that would equilize them with all other genpowers.

**Comment by xezon** [comment]
It is not clear to me why you started to raise this here and not in #1989, which was all about Particle Beam and Explosion damage. Nevertheless, the goal was to protect Internet Center against single attacks. This was achieved and Internet Center is better for it.

**Comment by ExiLe-ZH** [comment]
Keep in mind that most players spent their first point on the Spy Drone, that means you only have 2 to spent once you reach level 3 and can not unlock such combo until level 4. 

Also, if we further increase the HP threshold to withstand any combo aswell, then the IC truly becomes a fortress. Haven't we already reached our goal by making it to able to survive the strongest one shot power in the game?

**Comment by xezon** [comment]
Anything to add here in regards to Aurora damages?

**Comment by ExiLe-ZH** [comment]
Amount of Aurora's seems the same as vs SWs? But IC ofc bigger investment.

**Comment by xezon** [comment]
> Amount of Aurora's seems the same as vs SWs?

Yes. Exactly the same.

| Structure                          | No. Auroras to kill | No. Alpha Auroras to kill |
|------------------------------------|---------------------|---------------------------|
| Original Nuke Silo                 |  4                  |  3 (Dead before last fuel expl.) |
| **Patched Internet Center (this)** |  4                  |  3 (Dead before last fuel expl.) |

**Comment by xezon** [comment]
Jundiyy
> Looks good. Yes from me.

**Comment by ExiLe-ZH** [comment]
4 normal Aurora's sounds balanced ($10k), however 3 Alpha's sounds like too good of a trade, even if you lose them all. That's $6k vs $7.5k (+ future income damage). 

Maybe increase the threshold so that Hackers survive with 3 Alpha hits?

**Comment by xezon** [comment]
Documentation added. Title corrected. Looks good. Internet Center is strong.

**Pull request merged**
