### PR TITLE
Change: Remove Damage Effects From Immortal Buildings

### LINKED ISSUE #35: Supply stashes have damage effects but don't take any damage
Supply stashes should not have damage effects.

### PR DESCRIPTION
**Pull request by commy2**
- fix https://github.com/TheSuperHackers/GeneralsGamePatch/issues/35
- close https://github.com/TheSuperHackers/GeneralsGamePatch/pull/878

# before

https://user-images.githubusercontent.com/6576312/184477523-490354af-e4d0-410e-96e5-e4aa1116b118.mp4

# after

https://user-images.githubusercontent.com/6576312/184477527-c330d1fb-fca7-48b9-8252-18ad35ea5f28.mp4

### CODE REVIEW

**Comment by xezon** [comment]
I just tested this branch with shooting 5 Rockets from Helix onto Supply and it does sound the same as original.

**Comment by ExiLe-ZH** [comment]
> I just tested this branch with shooting 5 Rockets from Helix onto Supply and it does sound the same as original.

Because if many RPG's hit a target at the same time it creates a bigger explosion, which is what you hear, could be any target including the ground when you force fire.

**Comment by commy2** [comment]
Yeah, there are multiple sound and particle effects working here. The bigger explosion is when infantry missiles kill each other:

https://user-images.githubusercontent.com/6576312/184480004-6ab460cd-89f6-46fe-8293-7e079776646a.mp4

This effect can be removed by deleting:
Object TankHunterMissile/InstantDeathBehavior DeathModuleTag_03/FX_GenericMissileDeath

**Comment by xezon** [comment]
Before and After videos sound the same to me.

**Comment by commy2** [comment]
> Before and After videos sound the same to me.

The following recordings are made with this additional change:
```
-  FireSound = TankHunterWeapon
-  FireFX = FX_BuggyMissileIgnition
-  ProjectileDetonationFX = WeaponFX_RocketBuggyMissileDetonation
+  ;FireSound = TankHunterWeapon
+  ;FireFX = FX_BuggyMissileIgnition
+  ;ProjectileDetonationFX = WeaponFX_RocketBuggyMissileDetonation
```
which makes the Tank Hunter weapon silent.

# before this pull request


https://user-images.githubusercontent.com/6576312/184495426-d7d10acf-fc46-4d02-a853-223f740a3de0.mp4

# after this pull request

https://user-images.githubusercontent.com/6576312/184495492-894bce72-5609-427a-944d-69f453d90194.mp4

If this is about a different sound effect, then it is unrelated to Supply Docks.

**Review by xezon — APPROVED** [review]

**Pull request merged**
