### PR TITLE
Fix: Set correct name of Spectre Gunship for Spanish and Brazilian languages

### PR DESCRIPTION
**Pull request by xezon**
This change fixes the name of the Spectre Gunship for Spanish and Brazilian (Portuguese).

"Helicóptero Spectre" becomes "Avión de Spectre"

and

"Nave de Artilharia Spectre" becomes "Avião de Artilharia Spectre"

### CODE REVIEW

**Comment by commy2** [comment]
You speak Spanish or did someone report this?

**Comment by xezon** [comment]
Just a few words. Helicóptero means helicopter.

**Comment by xezon** [comment]
I suspect the translators misread gunship for
https://en.wikipedia.org/wiki/Gunship#Helicopter_gunships

Note that translators do not necessarily play the game. They just get a translation file and perhaps some additional context, but it can be lacking.

Likewise the Portuguese refers to naval ships, which Gunship can confuse to.

**Comment by xezon** [comment]
Preserve former key mapping for now.

**Comment by xezon** [comment]
Documentation added. Looks good.

**Comment by commy2** [comment]
Looks like the bold text messes with the kerning.

**Pull request merged**
