### PR TITLE
Add new dialog events for unused Generals unit descriptions

### PR DESCRIPTION
**Pull request by xezon**
* Relates to #176

This change adds new dialog events for unreferenced Generals unit descriptions. It is a copy from Generals Speech.ini.

```
dxoc001.wav    UnitDescriptLin01
dxoc002.wav    UnitDescriptLin02
dxoc003.wav    UnitDescriptLin03
dxoc004.wav    UnitDescriptLin04
dxoc005.wav    UnitDescriptLin05
dxoc006.wav    UnitDescriptLin06
dxoc007.wav    UnitDescriptLin07
dxoc008.wav    UnitDescriptLin08
dxoc009.wav    UnitDescriptLin09
dxoc010.wav    UnitDescriptLin10
dxoc011.wav    UnitDescriptLin11
dxoc012.wav    UnitDescriptLin12
dxoc013.wav    UnitDescriptLin13
dxoc014.wav    UnitDescriptLin14
dxoc015.wav    UnitDescriptLin15
dxoc016.wav    UnitDescriptLin16
dxoc017.wav    UnitDescriptLin17
dxoc018.wav    UnitDescriptLin18
dxoc019.wav    UnitDescriptLin19
dxoc020.wav    UnitDescriptLin20
dxoc021.wav    UnitDescriptLin21
dxoc022.wav    UnitDescriptLin22
dxoc023.wav    UnitDescriptLin23
dxoc024.wav    UnitDescriptLin24
dxoc025.wav    UnitDescriptLin25
dxoc026.wav    UnitDescriptLin26
dxoc027.wav    UnitDescriptLin27
dxoc028.wav    UnitDescriptLin28
dxoc029.wav    UnitDescriptLin29
dxoc030.wav    UnitDescriptLin30
dxoc031.wav    UnitDescriptLin31
dxoc032.wav    UnitDescriptLin32
dxoc033.wav    UnitDescriptLin33
dxoc034.wav    UnitDescriptLin34
dxoc035.wav    UnitDescriptLin35
dxoc036.wav    UnitDescriptLin36
dxoc037.wav    UnitDescriptLin37
dxoc038.wav    UnitDescriptLin38
dxoc039.wav    UnitDescriptLin39
dxoc040.wav    UnitDescriptLin40
dxoc041.wav    UnitDescriptLin41
dxoc042.wav    UnitDescriptLin42
dxoc043.wav    UnitDescriptLin43
dxoc044.wav    UnitDescriptLin44
dxoc045.wav    UnitDescriptLin45
dxoc046.wav    UnitDescriptLin46
dxoc047.wav    UnitDescriptLin47
dxoc048.wav    UnitDescriptLin48
dxoc049.wav    UnitDescriptLin49
dxoc050.wav    UnitDescriptLin50
dxoc051.wav    UnitDescriptLin51
dxoc052.wav    UnitDescriptLin52
dxoc053.wav    UnitDescriptLin53
dxoc054.wav    UnitDescriptLin54
dxoc055.wav    UnitDescriptLin55
dxoc056.wav    UnitDescriptLin56
dxoc057.wav    UnitDescriptLin57
dxoc058.wav    UnitDescriptLin58
dxoc059.wav    UnitDescriptLin59
dxoc060.wav    UnitDescriptLin60
dxoc061.wav    UnitDescriptLin61
dxoc062.wav    UnitDescriptLin62
dxoc063.wav    UnitDescriptLin63
dxou001.wav    UnitDescriptEva01
dxou002.wav    UnitDescriptEva02
dxou003.wav    UnitDescriptEva03
dxou004.wav    UnitDescriptEva04
dxou005.wav    UnitDescriptEva05
dxou006.wav    UnitDescriptEva06
dxou007.wav    UnitDescriptEva07
dxou008.wav    UnitDescriptEva08
dxou009.wav    UnitDescriptEva09
dxou010.wav    UnitDescriptEva10
dxou011.wav    UnitDescriptEva11
dxou012.wav    UnitDescriptEva12
dxou013.wav    UnitDescriptEva13
dxou014.wav    UnitDescriptEva14
dxou015.wav    UnitDescriptEva15
dxou016.wav    UnitDescriptEva16
dxou017.wav    UnitDescriptEva17
dxou018.wav    UnitDescriptEva18
dxou019.wav    UnitDescriptEva19
dxou020.wav    UnitDescriptEva20
dxou021.wav    UnitDescriptEva21
dxou022.wav    UnitDescriptEva22
dxou023.wav    UnitDescriptEva23
dxou024.wav    UnitDescriptEva24
dxou025.wav    UnitDescriptEva25
dxou026.wav    UnitDescriptEva26
dxou027.wav    UnitDescriptEva27
dxou028.wav    UnitDescriptEva28
dxou029.wav    UnitDescriptEva29
dxou030.wav    UnitDescriptEva30
dxou031.wav    UnitDescriptEva31
dxou032.wav    UnitDescriptEva32
dxou033.wav    UnitDescriptEva33
dxou034.wav    UnitDescriptEva34
dxou035.wav    UnitDescriptEva35
dxou036.wav    UnitDescriptEva36
dxou037.wav    UnitDescriptEva37
dxou038.wav    UnitDescriptEva38
dxou039.wav    UnitDescriptEva39
dxou040.wav    UnitDescriptEva40
dxou041.wav    UnitDescriptEva41
dxou042.wav    UnitDescriptEva42
dxou043.wav    UnitDescriptEva43
dxou044.wav    UnitDescriptEva44
dxou045.wav    UnitDescriptEva45
dxou046.wav    UnitDescriptEva46
dxou047.wav    UnitDescriptEva47
dxou048.wav    UnitDescriptEva48
dxou049.wav    UnitDescriptEva49
dxou050.wav    UnitDescriptEva50
dxou051.wav    UnitDescriptEva51
dxou052.wav    UnitDescriptEva52
dxou053.wav    UnitDescriptEva53
dxou054.wav    UnitDescriptEva54
dxou055.wav    UnitDescriptEva55
dxou056.wav    UnitDescriptEva56
dxou057.wav    UnitDescriptEva57
dxou058.wav    UnitDescriptEva58
dxou059.wav    UnitDescriptEva59
dxou060.wav    UnitDescriptEva60
dxou061.wav    UnitDescriptEva61
dxou062.wav    UnitDescriptEva62
dxou063.wav    UnitDescriptEva63
dxou064.wav    UnitDescriptEva64
dxou065.wav    UnitDescriptEva65
dxou066.wav    UnitDescriptEva66
dxog001.wav    UnitDescriptKen01
dxog002.wav    UnitDescriptKen02
dxog003.wav    UnitDescriptKen03
dxog004.wav    UnitDescriptKen04
dxog005.wav    UnitDescriptKen05
dxog006.wav    UnitDescriptKen06
dxog007.wav    UnitDescriptKen07
dxog008.wav    UnitDescriptKen08
dxog009.wav    UnitDescriptKen09
dxog010.wav    UnitDescriptKen10
dxog011.wav    UnitDescriptKen11
dxog012.wav    UnitDescriptKen12
dxog013.wav    UnitDescriptKen13
dxog014.wav    UnitDescriptKen14
dxog015.wav    UnitDescriptKen15
dxog016.wav    UnitDescriptKen16
dxog017.wav    UnitDescriptKen17
dxog018.wav    UnitDescriptKen18
dxog019.wav    UnitDescriptKen19
dxog020.wav    UnitDescriptKen20
dxog021.wav    UnitDescriptKen21
dxog022.wav    UnitDescriptKen22
dxog023.wav    UnitDescriptKen23
dxog024.wav    UnitDescriptKen24
dxog025.wav    UnitDescriptKen25
dxog026.wav    UnitDescriptKen26
dxog027.wav    UnitDescriptKen27
dxog028.wav    UnitDescriptKen28
dxog029.wav    UnitDescriptKen29
dxog030.wav    UnitDescriptKen30
dxog031.wav    UnitDescriptKen31
dxog032.wav    UnitDescriptKen32
dxog033.wav    UnitDescriptKen33
dxog034.wav    UnitDescriptKen34
dxog035.wav    UnitDescriptKen35
dxog036.wav    UnitDescriptKen36
dxog037.wav    UnitDescriptKen37
dxog038.wav    UnitDescriptKen38
dxog039.wav    UnitDescriptKen39
dxog040.wav    UnitDescriptKen40
dxog041.wav    UnitDescriptKen41
dxog042.wav    UnitDescriptKen42
dxog043.wav    UnitDescriptKen43
dxog044.wav    UnitDescriptKen44
dxog045.wav    UnitDescriptKen45
dxog046.wav    UnitDescriptKen46
dxog047.wav    UnitDescriptKen47
dxog048.wav    UnitDescriptKen48
dxog049.wav    UnitDescriptKen49
dxog050.wav    UnitDescriptKen50
dxog051.wav    UnitDescriptKen51
dxog052.wav    UnitDescriptKen52
dxog053.wav    UnitDescriptKen53
dxog054.wav    UnitDescriptKen54
dxog055.wav    UnitDescriptKen55
dxog056.wav    UnitDescriptKen56
dxog057.wav    UnitDescriptKen57
dxog058.wav    UnitDescriptKen58
dxog059.wav    UnitDescriptKen59
dxog060.wav    UnitDescriptKen60
dxog061.wav    UnitDescriptKen61
dxog062.wav    UnitDescriptKen62
dxog063.wav    UnitDescriptKen63
```

### CODE REVIEW

**Comment by xezon** [comment]
Documentation added.

It is not clear to me this is desired.

**Comment by kABUSE1** [comment]
I can't think of any good use-case for these.

**Comment by xezon** [comment]
Thanks for feedback. Then we can discard these.

**Comment by xezon** [comment]
Not needed.

**Pull request closed without merging**
