### PR TITLE
Change HERO experience reward of all faction tanks from 400 to 300

### PR DESCRIPTION
**Pull request by xezon**
Closes #726

Related to
* #395
* #412

HERO experience rewarded for killing any faction Tank, such as Crusader, Paladin, Avenger, Microwave, Battlemaster grants too much experience.

This change reduces all tank HERO experience points by 25%.

This change helps USA and China similarly. USA less, because it does not achieve many HERO Tank typically, as the main combat units are Humvee and Rocket soldiers. China Tank benefits the most, due its reliance on ELITE Battlemasters.

GLA Tanks already give 300 HERO experience or less.

# Stats

## Original
Killing 13 HERO tanks achieves 5 Star Promotion.

## Patched
Killing 17 HERO tanks achieves 5 Star Promotion.

## Original INI setups
```
ChinaTankBattleMaster
  ExperienceValue    = 100 100 200 400
  ExperienceRequired = 0 200 300 600

Tank_ChinaTankBattleMaster
  ExperienceValue    = 100 100 200 400
  ExperienceRequired = 0 200 300 600

Nuke_ChinaTankBattleMaster
  ExperienceValue    = 100 100 200 400
  ExperienceRequired = 0 200 300 600

Nuke_ChinaTankOverlord
  ExperienceValue    = 200 200 400 600
  ExperienceRequired = 0 400 600 1200

AmericaTankPaladin
  ExperienceValue    = 100 100 200 400
  ExperienceRequired = 0 200 300 600

AmericaTankCrusader
  ExperienceValue    = 100 100 200 400
  ExperienceRequired = 0 200 300 600

GLATankMarauder
  ExperienceValue    = 100 100 200 300
  ExperienceRequired = 0 200 300 600

GLATankScorpion
  ExperienceValue    = 60 60 120 200
  ExperienceRequired = 0 100 200 400

GLAVehicleQuadCannon
  ExperienceValue    = 50 50 100 150
  ExperienceRequired = 0 100 150 300

ChinaTankGattling
  ExperienceValue    = 50 50 100 150
  ExperienceRequired = 0 80 200 300

AmericaVehicleHumvee
  ExperienceValue    = 50 50 100 150
  ExperienceRequired = 0 100 150 300

ChinaVehicleHelix
  ExperienceValue    = 50 100 150 200
  ExperienceRequired = 0 100 200 400

AirF_AmericaJetRaptor
  ExperienceValue    = 75 75 125 175
  ExperienceRequired = 0 100 200 400

ChinaJetMIG
  ExperienceValue    = 50 50 100 150
  ExperienceRequired = 0 100 200 400

AirF_AmericaVehicleTomahawk
  ExperienceValue    = 50 50 100 150
  ExperienceRequired = 0 200 400 800

ChinaVehicleInfernoCannon
  ExperienceValue    = 50 50 100 150
  ExperienceRequired = 0 100 200 400

Nuke_ChinaVehicleNukeLauncher
  ExperienceValue    = 50 100 200 400
  ExperienceRequired = 0 400 600 1000

Demo_GLAVehicleRocketBuggy
  ExperienceValue    = 50 50 100 150
  ExperienceRequired = 0 200 400 800
```

### CODE REVIEW

**Comment by xezon** [comment]
commy2:
> If it were for me, I would've just made them all like the other vehicles.
> 50 -> 50 -> 100 -> 150
> I don't see how a Battle Master is harder to kill than a Gat. It takes 50% more RPG missiles to kill a Gat for example. 

Jundiyy:
> The hero units already benefit from the vet bonuses and now they benefit more from giving less xp
> I didn't check all properly, but if it was 240, feels quite less. I'd say 300 lowest

**Comment by commy2** [comment]
1.04 Scorpion: 60 -> 60 -> 120 -> 200

**Comment by ExiLe-ZH** [comment]
The whole balance of Tanks seems off, Quads and Humvees are often much harder to kill with less hard counters available, since they're so allround. Quads can even beat unvetted Tanks on their own while Gats can't.

Also is there often no differentiation between vet 0 and Vet 1 rewards, this is weird imo.

I would rebalance it to something like this:

> ChinaTankBattleMaster								
>   ExperienceValue    = **60** **80** **150** **300**
>   ExperienceRequired = 0 200 300 600
> 
> Tank_ChinaTankBattleMaster
>   ExperienceValue    = **60** **80** **150** **300**
>   ExperienceRequired = 0 200 300 600
> 
> Nuke_ChinaTankBattleMaster
>   ExperienceValue    = **80** **120** **150** **300**
>   ExperienceRequired = 0 200 300 600
> 
> Nuke_ChinaTankOverlord
>   ExperienceValue    = **150** 200 **350** **500**
>   ExperienceRequired = 0 400 600 1200
> 
> AmericaTankPaladin
>   ExperienceValue    = **80** **120** 200 400
>   ExperienceRequired = 0 200 300 600
> 
> AmericaTankCrusader
>   ExperienceValue    = **80** **120** 200 400
>   ExperienceRequired = 0 200 300 600
> 
> GLATankMarauder
>   ExperienceValue    = **80** **120** 200 300
>   ExperienceRequired = 0 200 300 600
> 
> GLATankScorpion
>   ExperienceValue    = 60 **80** 120 200
>   ExperienceRequired = 0 100 200 400
> 
> GLAVehicleQuadCannon
>   ExperienceValue    = 50 **80** **120** **200**
>   ExperienceRequired = 0 100 150 300
> 
> ChinaTankGattling
>   ExperienceValue    = 50 50 100 150
>   ExperienceRequired = 0 80 200 300
> 
> AmericaVehicleHumvee
>   ExperienceValue    = 50 **80** **150** **200**
>   ExperienceRequired = 0 100 150 300
> 

- Unvetted BM's are worse than Scorpions, hence I made them start from 60 aswell. 

- Nuke BM's are definitely harder to deal with than slow BM's for GLA, hence they start from 80.

- Overall reward for Overlords is a bit crazy, did a tiny nerf, since they can be hard countered quite easy in some cases.

- Made Quads from vet1 similar to Scorpion, because it's a pretty allround unit that's hard to deal with when vetted, harder than Gats, which has more hardcounters.

- Made Humvees bit higher for the same reasons as Quads and for making up for the fact that loaded MD's don't grant XP at all.

- Kept VETERAN/HERO USA Tanks original, as they're stronger than China's Tanks.

**Comment by MTKing4** [comment]
> Also made Humvee bit higher for the same reason the Quad and for making up the fact that loaded MD's don't grant XP at all.

Is this issue not fixable with a patch? I don't remember seeing a report for it

**Comment by ExiLe-ZH** [comment]
> > Also made Humvee bit higher for the same reason the Quad and for making up the fact that loaded MD's don't grant XP at all.
> 
> Is this issue not fixable with a patch? I don't remember seeing a report for it

https://github.com/TheSuperHackers/GeneralsGamePatch/issues/397

**Comment by xezon** [comment]
I believe this change is safe for starters. I see no reason that justifies 400 XP for any of the regular small tanks. 300 XP is much more reasonable, and still twice as high as other vehicles, such as Aircraft, Long range and Anti Air.

**Comment by commy2** [comment]
xezon, fyi, there is no need to modify the CINE_ (cinematic) variants of vehicles. They are copy pastes for campaign cutscenes with slight alterations. They are hopelessly outdated, with many being a frozen state of CCG 1.0. The reason I bother and pester about GC_ and Boss variants is, that they actually appear in single player and many scripted maps that feature the Boss Dozer.

**Comment by xezon** [comment]
I will revert the edits to CINE units then.

**Comment by xezon** [comment]
Just realized commy2 also opened a change for this:
* #412

**Comment by commy2** [comment]
HEROIC. HEROes are Burton, Kell and Mrs Lotus :)

**Comment by xezon** [comment]
Actually it is called HERO. See GameData.ini
```
  WeaponBonus = VETERAN  RATE_OF_FIRE  120%
  WeaponBonus = ELITE    RATE_OF_FIRE  140%
  WeaponBonus = HERO     RATE_OF_FIRE  160%
```

**Comment by commy2** [comment]
Nvm then. I am hallucinating apparently.

**Pull request closed without merging**
