### PR TITLE
Fix: Set unique default house color for Boss General

### PR DESCRIPTION
**Pull request by xezon**
This change sets a more appropriate default color for Boss General. Was green, is now gold, matching the red/yellow China GUI theme of Boss General better.

### CODE REVIEW

**Comment by commy2** [comment]
Where does this color appear?

**Comment by xezon** [comment]
I suspect this is default color in World Builder faction. Not sure.

**Comment by MTKing4** [comment]
Maybe give it a distinctive 4th color? So that Chinese boss units can be distinguished from actual Chinese units like overlords

I think Gold is a good choice for this

**Comment by xezon** [comment]
We can go with Yellow yes. Orange would also work.

**Comment by MTKing4** [comment]
I chose Yellow because it's a primary color, same as Red, blue and green

**Comment by xezon** [comment]
Boss default house color is now gold. Documentation added.

**Comment by xezon** [comment]
Documentation fixed. Looks good.

**Pull request merged**
