### PR TITLE
Fix: Add implementation of Partisans and Militia Man

### PR DESCRIPTION
**Pull request by commy2**
This implements the unused models for the broken Partisan worldbuilder unit. Could be placed on a fun map as third ai faction that attacks all/some players, similar to The Forgotten in C&C or Goblins/Wargs/Cave Trolls in BFME. It also implements the Milita Man model.

~I gave them AK Mob weapons for spice.~

I gave them custom dual uzi, shotgun, semi-automatic rifle weapons depending on the model.

For some reason, they all have parachute animations.

### CODE REVIEW

**Comment by commy2** [comment]
Found this unimplemented model too:

shot_20230807_230251_1

**Comment by commy2** [comment]
exploded death of MilitaMan needs fixing.

**Comment by xezon** [comment]
Nice stuff. My 2 cents:

### 1. No Militia guy potrait

Militia guy could also have that Partisan Portrait. Better than none. Because if he has none, it will show an empty slot in transporters and houses.

shot_20230808_183612_2

### 2. Muzzle flash of Militia guy is long

Muzzle flash of Militia guy looks a bit long. Model issue I think. Not a concern for this change.

shot_20230808_183724_12

### 3. No voices

Do other playable Civilian units like this have voices? If yes then this perhaps should too. Perhaps can just use GLA Rebel voices.

### 4. Shotgun Partisan fires machine gun

This guy has a shotgun like animation, but fires machine gun. Perhaps we can replace weapon with single shot to match the animation?

shot_20230808_184317_16

### 5. Enemy AI Militia guy does not attack Player

Perhaps also happens with the Partisan guys. I could not see, because USA just spawns the Partisan guys at the start.

shot_20230808_185036_18

### 6. Gun effects look different from faction solder guns

When Rangers & Co shoot then they will have lens flare and bullet case effects. Partisans have actual light emitters instead. Perhaps is better to make them look consistent if possible.

shot_20230808_185514_41

**Comment by commy2** [comment]
Yeah, it's because I gave them the Mob Ak47s. Could implement something more fitting for the respective models.

**Comment by commy2** [comment]
> Do other playable Civilian units like this have voices? If yes then this perhaps should too. Perhaps can just use GLA Rebel voices.

Unarmed civs never have voices. The only other armed civ is UN Soldier. Would have to check, but iirc, he does have neither voice nor portrait. UN Humvve and Milita Tank do not have voice or portraits either.

**Comment by MTKing4** [comment]
> ### 1. No Militia guy potrait
>
>Militia guy could also have that Partisan Portrait. Better than none. Because if he has none, it will show an empty slot in >transporters and houses.

Maybe do it with AI

**Comment by commy2** [comment]
I'm not so sure about the current Partisan portrait either. It's a GLA dude, possibly higher up. Doesn't really match the Partisans.

**Comment by commy2** [comment]
- should automatically attack now
- grant xp when killed (20)
- each one has a weapon according to the model

**Review by xezon — APPROVED** [review]
Good job with the weapons. Looks and sounds excellent. Bugs are fixed. Portrait does not look like a good match. Missing voice makes them not pleasant to control.

Remove the debug stuff before commit.

**Pull request merged**
