### PR TITLE
Fix: Prevent Jarmen From Sniping Pilot Of Landed Chinook or Helix

### LINKED ISSUE #35: Infantry does not evacuate from China Helix after it has been sniped by GLA Jarmen on the ground
Infantry does not evacuate from China Helix after it has been sniped by GLA Jarmen on the ground.

### LINKED ISSUE #180: Grounded USA Comanche cannot be sniped by GLA Jarmen
Grounded USA Comanche cannot be sniped by GLA Jarmen. China Helix (and USA Chinook?) can.

### LINKED ISSUE #661: China Helix does not evac passengers on snipe
Schermafbeelding 2022-03-25 om 13 03 29

bug where a helix that has infantry inside of its bunker that gets sniped by jarmen can not be recaptured.

Unsure if this was reported prior.

### PR DESCRIPTION
**Pull request by commy2**
- fix https://github.com/TheSuperHackers/GeneralsGameCode/issues/35
- fix https://github.com/TheSuperHackers/GeneralsGamePatch/issues/661
- close https://github.com/TheSuperHackers/GeneralsGamePatch/issues/180
- close TheSuperHackers/GeneralsGamePatch#876

Sniping Pilots does not work well with Helicopters that have units inside. Infantry won't evacuate and Helix may be unable to be captured despite being neutral. Arguably no Helicopter should be snipable, because Comanches aren't either.

### CODE REVIEW

**Comment by ExiLe-ZH** [comment]
Can't be made so they do evacuate and can be recaptured like other ground vehicles?

**Comment by commy2** [comment]
Engine issue.

**Comment by xezon** [comment]
I can't decide between this and the other (#876). What do we do :D

**Comment by commy2** [comment]
I don't know either. My instict is to not snipe helis. Planes cannot be sniped eithr when landed, and doing that would require engine changes as far as I can tell.

**Comment by xezon** [comment]
How about we make a video of the Helix snipe glitches? I can join you in a Multiplayer Session.

**Comment by Jundiyy** [comment]
I'd prefer to snipe Helis, I think it's quite a neat feature. Especially Chinooks and Helices.

**Comment by xezon** [comment]
I prefer no bugs. So I would like to test the ramifications of the Helicopter snipe.

**Comment by MTKing4** [comment]
Go with the snipe

**Pull request closed without merging**
