### PR TITLE
Change: Add more upgrade sound variations

### PR DESCRIPTION
**Pull request by xezon**
* Relates to #176

This change adds several unused upgrade sound variations. Only those that make sense and do not add confusion have been picked.

### WorkerVoiceUpgradeShoes

* iworu1a "I like my new shoes"

### RedGuardVoiceUpgradePatriotism

* iredu3a "Our patriotism will overwhelm the enemy"
* iredu3b "Patriotism will lead us to more victories"

### ChinookVoiceUpgradeSupplyLines

* vchiu1a "The Supply Lines are more efficient now"

### RaptorVoiceUpgradeCounterMeasures

* vrapu3d "Counter measures installed Sir"

### AuroraVoiceUpgradeBunkerBuster

* vauru1b "Bunker Buster bombs are ready Sir"
* vauru1c "The Bunker Buster bombs are now installed"

### CrusaderTankVoiceUpgradeDroneArmor

* vcruu3a "Drone Armor Upgrade's installed Sir"

### RangerVoiceUpgradeChemSuits

* iranu2a "These Chemical Suits are going to help"

### RebelVoiceUpgradeCashBounty

* irebu4b "The Cash Bounty will help our cause"
* ~~irebu4c "We will gain wealth for destroying the enemy"~~

### RebelVoiceUpgradeBoobyTrap

* irebu3c "Our Booby Traps will surprise the enemy"

### ToxinTractorVoiceUpgradeGamma

* vtoxu2c "The new Anthrax Gamma is here, General"

### BattleMasterTankVoiceUpgradeAutoLoader

* vbatu3c "The Auto Loaders will ensure our victory"

### BattleMasterTankVoiceUpgradeWeaponsGrade

* ~~vbatu5a "Weapons-grade Uranium shells are now available Sir"~~
* vbatu5b "The Weapons-grade Uranium shells will destroy the enemy"

### BattleMasterTankVoiceUpgradeFusion

* ~~vbatu4a "Fusion Reactor will make us faster"~~
* ~~vbatu4b "The Fusion Reactor upgrade is complete"~~

### CODE REVIEW

**Comment by commy2** [comment]
I do not like sound variations for upgrades. You can get only one global upgrade of each type per match, so variations are not needed. Instead, the recognizability is preferable.

**Comment by xezon** [comment]
It's a reasonable argument. I have accounted for this and mainly chosen variations that are similar to the singular original one.

Though, "We will gain wealth for destroying the enemy" is a bit of an outlier and candidate for removal. But all lines that explicitly mention the upgrade name from the start sound safe to me.

We can also make this optional if this would cause upset with some players.

**Comment by xezon** [comment]
I have demoted upgrade sound variation to Optional. They sound very good though in my opinion.

**Comment by xezon** [comment]
Also added the worker shoe upgrade variation "I like my new shoes" which sounds cute.

**Comment by xezon** [comment]
Discarding irebu4c "We will gain wealth for destroying the enemy" because it does not help understand that it refers to Cash Bounty upgrade, however it does explain the effect. Cash Bounty is no upgrade anyway, so it does not matter anyway.

Discarding vbatu5a "Weapons-grade Uranium shells are now available Sir" because it says "Sir" instead of "General". "Sir" fits USA speech only.

**Comment by xezon** [comment]
Discarding vbatu4a "Fusion Reactor will make us faster" and vbatu4b "The Fusion Reactor upgrade is complete" because the upgrade is actually called "Nuclear Tanks" upgrade.

**Comment by xezon** [comment]
The remaining upgrade voices sound good. They all say the name of the upgrade so there is no confusion about what they mean. Adds a little fresh touch to the game. 14 new sounds for 12 different upgrades.

**Comment by xezon** [comment]
Documentation added. Sounds good.

**Pull request merged**
