### PR TITLE
Fix premature hulk spawn

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase.**

* Related to #1163

This change fixes death wreck and debris spawn before model disappears.

Affects

* USA Microwave
* USA Laser Tank
* USA Tomahawk
* USA Sentry Drone
* China Nuke Cannon
* Militia Tank

Crusader Tank wreck was already fixed with #1163.

## Original

https://user-images.githubusercontent.com/4720891/216763444-5ec018bc-6862-45dd-a9ea-93a9713ce2da.mp4

### CODE REVIEW

**Comment by xezon** [comment]
There is still something wrong with Nuke Cannon death. First the Cannon disappears, then it reappears and a piece of debris flies that is from Chassis. I think the Rubble models need to be swapped.

https://user-images.githubusercontent.com/4720891/217615083-5cb4fafd-23d4-454e-845b-b92f07b2a1cd.mp4

**Comment by xezon** [comment]
Ok I have fix for it.

https://user-images.githubusercontent.com/4720891/217622929-a98d5aae-0ed9-42b0-aa6a-d24cee65799c.mp4

**Comment by xezon** [comment]
Still looks jank. I think it should look more like all the other China vehicles, without showing rubble model immediately.

**Comment by xezon** [comment]
I think this is good. This is how the other China vehicles die too.

https://user-images.githubusercontent.com/4720891/217629699-54204d6c-2cc0-439f-aa73-049531352211.mp4

**Comment by xezon** [comment]
Change looks good to me.

**Comment by commy2** [comment]
To fix the slop thing, have you tried using `Disposition = ON_GROUND_ALIGNED` on the OCLs?

**Comment by xezon** [comment]
What do you mean by slop thing?

**Comment by commy2** [comment]
slope*

**Comment by xezon** [comment]
I have noted what I tried here: #1610

**Pull request merged**
