### PR TITLE
Fix plane damage models and effects

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

This change fixes plane damage models and effects.

Fixes models for damaged states of

* AircraftCropDuster (non-consequential)

Adds transition damage effects for

* AircraftCropDuster
* AircraftCessna

The transition damage effect is the one that all faction Jets use too.

## Patched

https://user-images.githubusercontent.com/4720891/217061169-9d4459fb-281a-41eb-a66d-4f57ce95d93d.mp4

### CODE REVIEW

**Review by Stubbjax — APPROVED** [review]

**Comment by xezon** [comment]
Smoke Puff looked a bit too low in relation to height of planes. So I raised spawn height by 5 units. Looks better now.

shot_20230212_120803_1

**Comment by xezon** [comment]
Looks good to me.

**Comment by Stubbjax** [comment]
> Smoke Puff looked a bit too low in relation to height of planes. So I raised spawn height by 5 units. Looks better now.

It looks like it might obscure the plane a bit too much now?

**Comment by xezon** [comment]
Smoke just lasts shortly, so in motion this looks proper.

shot_20230212_121330_4

**Pull request merged**
