### PR TITLE
Fix: Civilian FarmerTruck now has correct model

### PR DESCRIPTION
**Pull request by xezon**
* Closes #1634

Civilian FarmerTruck now has correct model. CVFrmrtk.w3d & Co do not exist.

### CODE REVIEW

**Comment by Stubbjax** [comment]
What is the implication of this change? Can we see a before and after? Is this not a change that would be seen in-game?

**Comment by xezon** [comment]
Originally FarmerTruck is invisible. With this change it is visible.

invisible

**Comment by Stubbjax** [comment]
So this change doesn't just affect the world builder? The truck will be seen in-game now?

**Comment by xezon** [comment]
That depends whether or not it was placed in any official map. Since we have no automated way to check if it was referenced, we do not know.

**Comment by Stubbjax** [comment]
I'm curious why `FarmerTruck` exists when `TruckFarmer` seems to be the same thing? They are otherwise identical aside from the display name and geometry radius. Should the former just be deleted?

**Comment by xezon** [comment]
Deletion is also an option, but I did not want to go that far.

**Comment by Stubbjax** [comment]
> Deletion is also an option, but I did not want to go that far.

How is it far? It's clearly a busted duplicate. It'd be cleaning up the data and a net positive.

**Comment by xezon** [comment]
For example, if another Mod fixed the FarmerTruck like this change did, and then someone created a new Map for that Mod, then porting that Mod map to Patch104p will be more graceful, because FarmerTruck is present in both game builds.

**Comment by Stubbjax** [comment]
> For example, if another Mod fixed the FarmerTruck like this change did, and then someone created a new Map for that Mod, then porting that Mod map to Patch104p will be more graceful, because FarmerTruck is present in both game builds.

This does not make a whole lot of sense. Dedicated mod maps are not expected to work with 1.04 because they often contain other things from the mod.

**Comment by xezon** [comment]
Alternative change is #1634.

**Pull request closed without merging**
