### PR TITLE
Change: Add 3D shadows to big bombs

### PR DESCRIPTION
**Pull request by Stubbjax**
This change adds shadows to all carpet bombs (all weapon objects using the `EXCarptBmb` model). This makes it much easier to determine the height and trajectory of the bomb.

Values were copied from other aircraft so that the shadow aligns with them.

---

Where is the bomb going to land?

image

It's much clearer now!

image

_I can see many shadows appearing in the distance._

### CODE REVIEW

**Comment by MTKing4** [comment]
Very Nice

Is this the New Bomb Model we made? it looks like it

**Comment by xezon** [comment]
Perhaps add it to all other bombs as well then? MOAB & Co.

**Comment by xezon** [comment]
Documentation added. 3D shadows added to objects using models EXAMine_A and AVBomber_B. Not added to object using PMMoab, because the shadow somehow does not show for it. I could not figure out why.

**Review by xezon — APPROVED** [review]
Looks good.

**Pull request merged**
