### PR TITLE
Change: Improve voice setup of USA Stealth Fighter

### PR DESCRIPTION
**Pull request by xezon**
* Relates to #176

This change adds 1 new sound to the USA Stealth Fighter. The sound has been assembled for English, French, German, (Russian).

### StealthFighterVoiceCreate

* ~~vstesea "Ready for covert mission"~~
* vsteseg "Stealth Fighter, ready for take-off"

### CODE REVIEW

**Comment by MTKing4** [comment]
Please stop changing Creation Voicelines, people have gotten used to original ones and this change not only is unnecessary but will cause confusion

You can just add the new sounds to the select, don't mess with the creation

**Comment by xezon** [comment]
Demoted to optional bundle pack.

**Comment by MTKing4** [comment]
Just to be clear, I would still like the new Voicelines added to selection, and the creation change is the only one that should be optional

**Comment by xezon** [comment]
"Stealth Fighter, ready for take-off" is no fit voice line for selection.

**Comment by MTKing4** [comment]
Hmm fair enough

**Comment by xezon** [comment]
Documentation added. Sounds good.

**Pull request merged**
