### PR TITLE
Add: Implemention Of Radar Station Tech Building As Prop

### PR DESCRIPTION
**Pull request by commy2**
Don't mind me, just having fun.

https://user-images.githubusercontent.com/6576312/137602147-1ea7d0a6-6ca5-4ee8-8e4f-54a7f2742b7b.mp4

### CODE REVIEW

**Comment by xezon** [comment]
What is the plan for this change?

**Comment by commy2** [comment]
I have no plans for this lol

**Comment by xezon** [comment]
Ok. So can close it?

**Comment by commy2** [comment]
Okay, here's the plan.

We implement the unused tech building, since the change is basically free (a few kB of code, no assets). We don't make it do anything, but let potential map makers decide what to do with it.

Commented out the gap generator code. It now is basically a capturable prop.

**Comment by xezon** [comment]
Sounds good.

**Review by xezon — APPROVED** [review]

**Pull request merged**
