### PR TITLE
Remove custom PlacementViewAngle of vehicles

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

This change removes custom PlacementViewAngle of vehicles. This way, placement view angle is consistent when placing vehicles in World Builder.

Affects
* All GLA Battle Bus objects
* All USA Avenger Laser Turret objects
* All China Helix Propaganda, Bunker attachment objects
* All China Overlord Propaganda, Bunker attachment objects

### CODE REVIEW

**Review by Stubbjax — APPROVED** [review]
image

Makes me sad.

**Comment by xezon** [comment]
Note that all INI comments are stripped away by Mod Builder on build step, so adding INI comments is inconsequential for a release.

**Comment by commy2** [comment]
Why make the dashed lines longer? They are purposefully set to 79 chars, so the code shows up in any 80 wide text editor + scrollbar.

**Comment by xezon** [comment]
Ok I will make it shorter.

**Comment by xezon** [comment]
Comments and dashed lines shortened.

**Pull request merged**
