### PR TITLE
Fix: Nuke General Mig Tooltip

### PR DESCRIPTION
**Pull request by commy2**
The tooltip of the Nuke Mig says that it "creates a fire-storm in large groups".
It does not create a fire storm.

### CODE REVIEW

**Comment by ExiLe-ZH** [comment]
Implement Nuclear Storm pls

**Comment by commy2** [comment]
No.

**Comment by ExiLe-ZH** [comment]
> No.

Why not? 🙁

**Review by xezon — APPROVED** [review]

**Comment by commy2** [comment]
> Why not? 🙁

The first mod I ever made was turning the missiles of the Scud Storm into the Chinese nuke missiles. A classmate wanted that back in like 2004.
It was fun.

**Pull request merged**
