### PR TITLE
Fix: Factory Door Animation Damage Transitions

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixed door animations resetting when transitioning between damage states for vehicle production buildings (GLA Arms Dealer + China War Factory + USA War Factory).

## 1.04:
When the War Factory transitions between damage states, the door animation state is reset.

https://user-images.githubusercontent.com/11547761/196031878-4fa989b2-c5ec-4a87-b479-92e106172ba3.mp4

## Patch:
When the War Factory transitions between damage states, the door animation state is maintained.

https://user-images.githubusercontent.com/11547761/196031884-4bd62cc6-1994-4db5-b4e4-f99c2f1ec3e0.mp4

### CODE REVIEW

**Comment by xezon** [comment]
Oh wow I love it. A bug that everyone has noticed.

What about USA, China Airfield doors? And China, USA Command Center. They might have same issue.

**Comment by Stubbjax** [comment]
> Oh wow I love it. A bug that everyone has noticed.
> 
> What about USA, China Airfield doors? And China, USA Command Center. They might have same issue.

Yep, a bunch of buildings require the same treatment. I was going to do those in separate pull requests but I can append them to this one if you believe it is preferable?

**Comment by xezon** [comment]
As you wish.

**Review by xezon — APPROVED** [review]

**Comment by ExiLe-ZH** [comment]
Mega pro ++++++++++++

**Review by commy2 — CHANGES_REQUESTED** [review]
GC Stealth and Tox missing.

**Review by commy2 — APPROVED** [review]
Very nice.

**Pull request merged**
