### PR TITLE
Fix: USA Sentry Drone art issues

### LINKED ISSUE #1160: USA Sentry Drone texture has black stripes
USA Sentry Drone texture has black stripes.

shot_20220908_130519_5

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1160

## Original

shot_20220915_123023_1

## Patched, NProject

shot_20220915_122855_1

### CODE REVIEW

**Comment by xezon** [comment]
Sentry Drone cameo fix to be done in separate change later.

**Review by Stubbjax — DISMISSED** [review]
Looks great!

**Comment by xezon** [comment]
I think this change is now obsolete. I am not sure what is inside the W3D, but most jank is inside texture, which is now fixed properly with
* #1227

**Comment by xezon** [comment]
NProject obsolete. Closing.

**Pull request closed without merging**
