### PR TITLE
Fix firing elevation limits

### PR DESCRIPTION
**Pull request by xezon**
* old PR: #111

All weapons which previously had TargetPitch parameters no longer have this. This allows them to acquire targets regardless of minor elevation differences.

### CODE REVIEW

**Comment by ExiLe-ZH** [comment]
Does this also fix Dragons missing/not clearing elevated bunkers?

**Comment by commy2** [comment]
No, seems only to be for shell based weapons. Tanks, Fire Base, Strat Center ... and Angry Mob Molotov for some reason.

**Comment by xezon** [comment]
We tested this already. With this change tanks can shoot up and down any steep terrain. Realistically we can only close this, but I will leave it open for now for reference, because this is ongoing investigation.

**Comment by xezon** [comment]
Actually, we can close already, it is linked in the other Pull Request, so can be viewed from there.

**Pull request closed without merging**
