### PR TITLE
Change: Increase regular China Black Lotus Vehicle Hack range by +30%

### PR DESCRIPTION
**Pull request by xezon**
Related:
* #790 
* #434

This change adds 30% range on top of all China Black Lotus vehicle hacks, except of Super Lotus.

Black Lotus can now try engage idle tanks. When idle, meaning no guard or retaliation, Black Lotus can successfully disable tanks without getting shot at. However, when tanks are on duty, Lotus can be attacked as usual.

## Relevant ranges
| Object | Hack Range | Attack Range | Stealth Detection Range |
|--------|-----------:|-------------:|------------------------:|
| Most Tanks               |     | 150 |     |
| USA Tomahawk             |     | 300 |     |
| China Overlord           |     | 175 |     |
| China Overlord Gattling  |     | 225 | 200 |
| China Inferno            |     | 300 |     |
| GLA Marauder             |     | 170 |     |
| GLA Rocket Buggy         |     | 300 |     |
| USA Scout Drone          |     |     | 150 (+75+10 wander) |
| GLA Radar Van            |     |     | 250 |
| China Outpost            |     |     | 300 |
| Original Super Lotus     | 300 |     | 300 |
| Original Lotus           | 150 |     | 300 |
| **Patched Lotus (this)** | 195 |     | 300 |

Original and patched vehicle hack range of Black Lotus is significantly lower than all main stealth scouts. USA Scout drone sways around USA vehicles in idle by 35 and on the move or attack by 75 + another 10, which puts it well within Lotus range, even after Patch.

Patched Black Lotus vehicle hack range is greater than all main weapons of regular Tanks.

# Lab Test

Find comparison tables below as to how much damage Lotus receives when trying to disable tanks on guard. Note that these are lab tests, without regular battle scenarios. Factors such as unit movements prior Lotus hack, assisting unit constellations, manual attack delay and latency are not and cannot be considered.

Note 1: Lotus was always pulled away from enemy forces as soon as the target vehicle was disabled.

Note 2: Super Lotus will disable all vehicles listed below without receiving any damage.

Note 3: No tests vs Toxin Tanks.

## Lotus vs GLA Technical on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x GLA Technical from behind  | 33%  |  0% |
| 1x GLA Technical from front   | 50%  |  0% |
| 2x GLA Technical from behind  | 50%  | 20% |
| 2x GLA Technical from front   | 100% | 40% |
| 3x GLA Technical from behind  | 90%  | 33% |
| 3x GLA Technical from front   | 100% | 50% |

## Lotus vs GLA Quad on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x GLA Quad from behind  | 60%  |   0% |
| 1x GLA Quad from front   | 80%  |  20% |
| 2x GLA Quad from behind  | 100% |  75% |
| 2x GLA Quad from front   | 100% | 100% |
| 3x GLA Quad from behind  | 100% | 100% |
| 3x GLA Quad from front   | 100% | 100% |

## Lotus vs Rocket Scorpion on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x GLA Rocket Scorpion from behind  | 60%  |   0% |
| 1x GLA Rocket Scorpion from front   | 60%  |  60% |
| 2x GLA Rocket Scorpion from behind  | 100% |  50% |
| 2x GLA Rocket Scorpion from front   | 100% | 100% |
| 3x GLA Rocket Scorpion from behind  | 100% |  90% |
| 3x GLA Rocket Scorpion from front   | 100% | 100% |

## Lotus vs China Gattling on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x China Gattling from behind  | 20%  |   5% |
| 1x China Gattling from front   | 33%  |  25% |
| 2x China Gattling from behind  | 100% |  50% |
| 2x China Gattling from front   | 100% | 100% |
| 3x China Gattling from behind  | 100% | 100% |
| 3x China Gattling from front   | 100% | 100% |

## Lotus vs Nuke China Battlemaster on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x Nuke China Battlemaster from behind  | 33% |   0% |
| 1x Nuke China Battlemaster from front   | 33% |  25% |
| 2x Nuke China Battlemaster from behind  | 50% |  20% |
| 2x Nuke China Battlemaster from front   | 60% |  40% |
| 3x Nuke China Battlemaster from behind  | 60% |  33% |
| 3x Nuke China Battlemaster from front   | 80% |  66% |

## Lotus vs China Gattling Overlord on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x China Gattling Overlord from behind  | 100% |   0% |
| 1x China Gattling Overlord from front   | 60%  |  25% |

## Lotus vs Nuke China Overlord on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x Nuke China Overlord from behind  |   0% |   0% |
| 1x Nuke China Overlord from front   |  40% |  20% |
| 2x Nuke China Overlord from behind  |   5% |   0% |
| 2x Nuke China Overlord from front   |  85% |  40% |
| 3x Nuke China Overlord from behind  |  50% |   0% |
| 3x Nuke China Overlord from front   | 100% |  60% |

## Lotus vs Nuke China Propaganda Overlord on Guard

| _______________ Enemy Object(s) _______________ | Original Lotus recv DMG | Patched Lotus recv DMG (this) |
|-------------------------------------------------|------------------------:|-------------------------------:|
| 1x Nuke China Prop Overlord from behind  |   0% |   0% |
| 1x Nuke China Prop Overlord from front   |  33% |  25% |

### CODE REVIEW

**Comment by EnigmaZift** [comment]
I would suggest to reduce the delay for hacking rather than increasing the range. For one particular reason, once a Lotus has "latched on" to a hack, she will continue the hack no matter how far the target gets. 

For this reason, she has 150 hack range - which is equal to the vast majority of range for ground units. Right?

So my alternative suggestion is to drop the actual hack time by maybe 1 second (20% improvement), and she will take equally less damage as if she had more range (the units will close the range either way and do some amount of damage, this way is more fair than increased range which comes with dangerous implications at times)

**Comment by xezon** [comment]
Black Lotus hack times are already very good.
```
UnpackTime       = 2000
PackTime         = 1000
PreparationTime  = 2000
```
150 Hack Range is really not good. See test results above.

**Comment by Jundiyy** [comment]
Yes, increase hack range.

**Comment by xezon** [comment]
I am still not so sure about the 30% jump. Although the lab tests look very good on the 195 AttackRange, I do think that in combination with the faster Lotus level up and thus self heal capabilities, Lotus would also be ok with tanking some damage on Vehicle Hack. In that case a range of 180 (from 150) could be sufficient.

**Comment by Jundiyy** [comment]
280 sounds good as well.

**Comment by Jundiyy** [comment]
I mean 180, not 280 lol. 195 and 180 are both better than original. Looking at the 195 table, I think it still looks safe to do.

**Comment by xezon** [comment]
280 lets goooooooooooo

**Pull request closed without merging**
