### PR TITLE
Fix: Nuke Battlemaster Detonation Effect Has Offset

### PR DESCRIPTION
**Pull request by xezon**
This change fixes detonation offset of Nuke Battlemaster. The fix uses same principles as
* #1122

### Original

https://user-images.githubusercontent.com/4720891/205148273-7354f628-6c53-49f1-a694-a4e61052663a.mp4

### CODE REVIEW

**Comment by Stubbjax** [comment]
Does this mean it will be harder for Nuclear Battlemaster explosions to hit Humvees?

**Comment by ExiLe-ZH** [comment]
Was thinking the same thing, it'll be a pretty huge nerf if becomes easier for units to stay out of the explosion radius of rushing BMs.

**Comment by commy2** [comment]
The explosion damage location is not changed by this PR. The effect will be displayed where the damaged is actually dealt in 1.04: at the center of the wreck.

~~What is moved back however is the radiation field.~~

Correction: the radiation field is created at the same position before and after the patch. This makes this change entirely visual.

**Comment by commy2** [comment]
I see another visual glitch. The muzzle fire is displayed when the tank is blown up.

**Review by commy2 — APPROVED** [review]

**Pull request merged**
