### PR TITLE
Change: Add suicide car bomb ability to Civilian AircraftCropDuster

### PR DESCRIPTION
**Pull request by xezon**
This change adds suicide car bomb ability to Civilian AircraftCropDuster, ~~Scooter~~.

Note that other carts and planes can also be used by bombers already.

https://user-images.githubusercontent.com/4720891/217649930-f6ae893e-02c0-46f2-8e46-c576927308da.mp4

### CODE REVIEW

**Comment by commy2** [comment]
Alternative would be preventing Terrorists from entering these. Just like how it makes no sense for Hijackers to enter Combat Bikes, it makes no sense for Terrorists to hijack Scooters with the driver still around.

**Comment by xezon** [comment]
Bombers can also enter the Ox thingy and the Horse Cart, which have no Human drivers at all. I don't know, I would make it interactive. That is what these Civilian Cars are for. For everything else there are props.

**Comment by commy2** [comment]
They would be better props if Terrorists couldn't enter them.

**Comment by xezon** [comment]
Up to the map designer. For fun maps these cars are ok.

**Pull request merged**
