### PR TITLE
Fix: avavnger textures

### PR DESCRIPTION
**Pull request by xezon**
This change reworks avavnger (USA Avenger) textures. The damaged textures are remade by borrowing pieces from original Humvee.

### avavnger

* Fixes black seams on roof
* Fixes white seams on tire profiles
* Removes 3 black dots from trunk
* Brightens sides of trunk to better blend with chassis
* ~~Reduces green color tint to look cleaner and more distinct from Humvee~~
* Fixes black seams on hood, window, back, side
* Fixes brightness mismatch on tires
* Fixes contrast of bolts

### avavnger_d, avavnger_e

* Fixes black seams on roof
* Fixes white seams on tire profiles
* Removes 3 black dots from trunk
* Brightens sides of trunk to better blend with chassis
* Fixes black seams on hood, back
* Fixes brightness mismatch on tires
* Removes all junk of original _D and _E
* Fixes strong color tint
* Repaints shattered glass
* Repaints burns on back door, roof
* Repaints bullet holes

## Original

shot_20220922_091848_2

## Patched

shot_20220922_091021_1

## Original

shot_20220922_092006_3

## Patched

shot_20220922_091232_2

### CODE REVIEW

**Comment by MTKing4** [comment]
Windows are no longer broken

**Comment by xezon** [comment]
Yes. Damaged windows now looks same as Humvee, Ambulance.

**Comment by MTKing4** [comment]
I kinda like the damaged windows

**Comment by xezon** [comment]
> I kinda like the damaged windows

Understandable. The way they drawn is the pinnacle of artist mastery.

windows

**Comment by MTKing4** [comment]
that is a 2003 game for you 😄 

also, no one will zoom in that close to see it, because if they do, they'll see that all infantry units have a triangle for a face

**Comment by xezon** [comment]
The textures hold up pretty well for a game that old. It is just some bits and pieces that are lazy drawn. Other pieces are very well done.

**Comment by xezon** [comment]
I appended one more improvement as I noticed there is a bright fine seam between the back windows and trunk cargo platform. Fixed.

**Comment by ExiLe-ZH** [comment]
I like it better with broken windows and bullet holes, even though it's all low res. It overall looks more war-torn and less plain, from a distance it looks convincing enough.

**Comment by xezon** [comment]
Flaws of the original texture:
* Poorly drawn window cracks
* Poorly drawn and placed bullet holes (do not blend at all with surroundings)
* Poorly drawn and placed damage junk (do not blend at all with surroundings)
* Awfully stretched drivers roof
* No dark burn at the front where the smoke is emitted
* Bullet holes on the tires, partly clip onto the rubber and do not blend with the rim
* No light transition on trunk bed at the sides
* Inconsistent art style compared to Humvee, Ambulance, which are essentially the same chassis

**Comment by xezon** [comment]
New edit pushed with repainted shattered glass.

shot_20220926_083401_3

**Comment by xezon** [comment]
Improvements pushed.

* Added bullet holes to _d and _e textures
* Fixed black seams on roof
* Fixes white seams on tire profile
* Improved shattered glass
* Reverted tint change

**Comment by xezon** [comment]
I fixed a few more minor things on chassis. The model texture mapping needs some fixing. Housecolors and tires look bad.

shot_20221118_210852_1

**Comment by xezon** [comment]
Looks okay to me. Brightness levels match Ambulance Humvee.

**Pull request merged**
