### PR TITLE
Add test map for all factions

### PR DESCRIPTION
**Pull request by MTKing4**
A map with all factions and sub-factions

### CODE REVIEW

**Review by xezon — CHANGES_REQUESTED** [review]
Please add a better title for this change.
Also please use "Test" prefix for test map and pick a name that makes its intent descriptive. It is not clear what `JackOfAllTrades` means.

**Comment by MTKing4** [comment]
i changed the title, i could make the map name with the same name? `MapWithAllFactions`

**Comment by xezon** [comment]
How about `TestAllFactions` ?

**Review by MTKing4 — COMMENTED** [review]
fixed

**Review by xezon — APPROVED** [review]

**Pull request merged**
