### PR TITLE
Fix: Aurora Alpha Fuel Air Explosion May Trigger Before Bomb Hits

### LINKED ISSUE #15: Sometimes Aurora Alpha fuel bomb does not happen after initial bomb it dropped on target
Sometimes Aurora Alpha fuel bomb does not happen after initial bomb it dropped on target. Fixable?

Haubibban:
> Put a unit behind the tall structure and order Alpha to attack it from opposite side

### PR DESCRIPTION
**Pull request by commy2**
- fix https://github.com/TheSuperHackers/GeneralsGamePatch/issues/15

ZH 1.04

- The Aurora Alpha secondary fuel air explosion is created where the bomb first collides with a building instead of where the bomb actually hits.

After change:

- The secondary explosion is triggered when the primary bomb explodes.

Note: This is related to https://github.com/TheSuperHackers/GeneralsGamePatch/issues/283. It does however not fix that issue. That issue is also still under discussion, since it has gameplay / balance considerations.

### CODE REVIEW

**Comment by xezon** [comment]
From my side this is ok, but would prefer if @alanblack166, @ThePredatorBG or GeneralCamo look over this, because it is not clear to me if such a weapon change could have unintentional side effects.

**Comment by MTKing4** [comment]
Wait does that mean that the fuel air explosion triggers instantly now?

**Comment by commy2** [comment]
> Wait does that mean that the fuel air explosion triggers instantly now?

No. It triggers after the same delay. However, in 1.04, it actually triggers when the primary bomb dies. The primary bomb dies once it collides with a structure. However, the primary bomb dying does not start the primary explosion. The "dead" bomb continues towards the target.

This means that the secondary explosion happens where the bomb first collides, instead of where the projectile actually hits.

**Comment by MTKing4** [comment]
So now when the bomb dies, nothing happens?

**Comment by commy2** [comment]
After patch: When the bomb dies, i.e. phases through a building, it still continues until it hits its target. Once it hits the target, it will cause the primary explosion damage. After 1 second, the secondary explosion will trigger where the first one was.

**Comment by MTKing4** [comment]
Hmmm, that's not good, gonna make alpha auroras more OP and easier to kill targets and nightmare for dozers (can't hide behind buildings anymore)

Maybe it will be better if the bomb dies completely if it hits another building

Nice sketch btw :)

**Comment by commy2** [comment]
> can't hide behind buildings anymore

They already die to the primary hit in 1.04. This would only be an issue if you group multiple dozers behind the same building.

> Maybe it will be better if the bomb dies completely if it hits another building

Maybe, but then this would drastically expand the scope of this change. Then we'd have to change all Auroras, and probably a lot of other units with the MissileAIUpdate logic driving the projectile.

**Comment by MTKing4** [comment]
> They already die to the primary hit in 1.04. This would only be an issue if you group multiple dozers behind the same building.

Not always, buildings save the dozers often, especially if high enough to detonate the bomb as far as possible from the dozer

> Maybe, but then this would drastically expand the scope of this change. Then we'd have to change all Auroras, and probably a lot of other units with the MissileAIUpdate logic driving the projectile.

Making the bomb phase through is what would drastically expand the scope of this change, all other auroras bombs just colide and explode on contact with any building, others have rockets not bombs, and still collide, only alpha aurora has this issue, so fixing it to be consistent with the other bombers the better approach imo

**Comment by xezon** [comment]
It certainly is reasonable to suggest that bomb shell and bomb fuel may both explode at P1 instead of P2.

**Comment by commy2** [comment]
> Not always, buildings save the dozers often, especially if high enough to detonate the bomb as far as possible from the dozer

Yeah, if the building is on the enemy side of the Aurora, the building will catch the bomb... including the secondary explosion. This change does not make the bomb phase through buildings. It makes the secondary explosion happen where the bomb hit in cases if the bomb already phased through the building.

> Making the bomb phase through is what would drastically expand the scope of this change, all other auroras bombs just colide and explode on contact with any building, others have rockets not bombs, and still collide, only alpha aurora has this issue, so fixing it to be consistent with the other bombers the better approach imo

That's not what this change does. Making bombs phase through more buildings would be a bad idea, we agree on that. No one wants that. However, it already does on neutral and friendly buildings, and I don't think changing that is in scope for this.

**Comment by MTKing4** [comment]
Yeah i misunderstood my bad, i get it now

Then now we should fix the issue of when bombs phase through :D

**Review by alanblack166 — APPROVED** [review]

**Pull request merged**
